version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "kcenon"
    labels:
      - "dependencies"
      - "github-actions"

  # Enable version updates for git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "kcenon"
    labels:
      - "dependencies"
      - "submodules"