Common System: examples/adapter_pattern_example.cpp File Reference
adapter_pattern_example.cpp File Reference
#include <kcenon/common/adapters/adapter.h>
#include <iostream>
#include <memory>
#include <string>
Classes
class DataService
Functions
template<typename T >
void use_service (const adapter< T > &svc)
int main ()
Function Documentation
main()
int main ()
Definition at line 45 of file adapter_pattern_example.cpp.
{
    std::cout << "=== Adapter Pattern Example ===\n\n";
    // 1. Wrap a shared_ptr
    std::cout << "1. Shared pointer adapter:\n";
    {
        auto service = std::make_shared<DataService>("SharedService");
        auto adapted = adapter(service);
        std::cout << "   Name via ->: " << adapted->get_name() << "\n";
        use_service(adapted);
    }
    // 2. Wrap a unique_ptr
    std::cout << "\n2. Unique pointer adapter:\n";
    {
        auto service = std::make_unique<DataService>("UniqueService");
        auto adapted = adapter(std::move(service));
        std::cout << "   Name via ->: " << adapted->get_name() << "\n";
        std::cout << "   Raw ptr: " << (adapted.get() != nullptr ? "valid" : "null") << "\n";
    }
    // 3. Use make_shared_adapter helper
    std::cout << "\n3. make_shared_adapter helper:\n";
    {
        auto adapted = make_shared_adapter<DataService>("FactoryService");
        std::cout << "   Name: " << adapted->get_name() << "\n";
        adapted->process();
    }
    // 4. Adapter traits inspection
    std::cout << "\n4. Adapter traits:\n";
    {
        using shared_traits = adapter_traits<std::shared_ptr<DataService>>;
        using unique_traits = adapter_traits<std::unique_ptr<DataService>>;
        std::cout << "   shared_ptr is_smart_pointer: "
                  << (shared_traits::is_smart_pointer ? "true" : "false") << "\n";
        std::cout << "   shared_ptr supports_weak: "
                  << (shared_traits::supports_weak ? "true" : "false") << "\n";
        std::cout << "   unique_ptr is_smart_pointer: "
                  << (unique_traits::is_smart_pointer ? "true" : "false") << "\n";
        std::cout << "   unique_ptr supports_weak: "
                  << (unique_traits::supports_weak ? "true" : "false") << "\n";
    }
    std::cout << "\nDone.\n";
    return 0;
}
References kcenon::common::adapters::adapter(), kcenon::common::adapters::make_shared_adapter(), and use_service().
use_service()
template<typename T > void use_service (const adapter< T > & svc)
Examples
adapter_pattern_example.cpp.
Definition at line 39 of file adapter_pattern_example.cpp.
{
    std::cout << "   Pointer valid: " << (svc.get() != nullptr ? "true" : "false") << "\n";
    svc->process();
}
References kcenon::common::adapters::adapter< T, Traits >::get().
Referenced by main().