var annotated_dup =
[
    [ "kcenon", "namespacekcenon.html", [
      [ "common", "namespacekcenon_1_1common.html", [
        [ "adapters", "namespacekcenon_1_1common_1_1adapters.html", [
          [ "adapter", "classkcenon_1_1common_1_1adapters_1_1adapter.html", "classkcenon_1_1common_1_1adapters_1_1adapter" ],
          [ "adapter_base", "classkcenon_1_1common_1_1adapters_1_1adapter__base.html", "classkcenon_1_1common_1_1adapters_1_1adapter__base" ],
          [ "adapter_factory", "classkcenon_1_1common_1_1adapters_1_1adapter__factory.html", "classkcenon_1_1common_1_1adapters_1_1adapter__factory" ],
          [ "adapter_traits", "structkcenon_1_1common_1_1adapters_1_1adapter__traits.html", "structkcenon_1_1common_1_1adapters_1_1adapter__traits" ],
          [ "adapter_traits< std::shared_ptr< T > >", "structkcenon_1_1common_1_1adapters_1_1adapter__traits_3_01std_1_1shared__ptr_3_01T_01_4_01_4.html", "structkcenon_1_1common_1_1adapters_1_1adapter__traits_3_01std_1_1shared__ptr_3_01T_01_4_01_4" ],
          [ "adapter_traits< std::unique_ptr< T, Deleter > >", "structkcenon_1_1common_1_1adapters_1_1adapter__traits_3_01std_1_1unique__ptr_3_01T_00_01Deleter_01_4_01_4.html", "structkcenon_1_1common_1_1adapters_1_1adapter__traits_3_01std_1_1unique__ptr_3_01T_00_01Deleter_01_4_01_4" ],
          [ "interface_adapter", "classkcenon_1_1common_1_1adapters_1_1interface__adapter.html", "classkcenon_1_1common_1_1adapters_1_1interface__adapter" ],
          [ "smart_adapter_factory", "classkcenon_1_1common_1_1adapters_1_1smart__adapter__factory.html", "classkcenon_1_1common_1_1adapters_1_1smart__adapter__factory" ]
        ] ],
        [ "bootstrap", "namespacekcenon_1_1common_1_1bootstrap.html", [
          [ "SystemBootstrapper", "classkcenon_1_1common_1_1bootstrap_1_1SystemBootstrapper.html", "classkcenon_1_1common_1_1bootstrap_1_1SystemBootstrapper" ]
        ] ],
        [ "config", "namespacekcenon_1_1common_1_1config.html", [
          [ "cli_config_parser", "classkcenon_1_1common_1_1config_1_1cli__config__parser.html", "classkcenon_1_1common_1_1config_1_1cli__config__parser" ],
          [ "cli_option", "structkcenon_1_1common_1_1config_1_1cli__option.html", "structkcenon_1_1common_1_1config_1_1cli__option" ],
          [ "cli_parse_result", "structkcenon_1_1common_1_1config_1_1cli__parse__result.html", "structkcenon_1_1common_1_1config_1_1cli__parse__result" ],
          [ "CliConfigParser", "classkcenon_1_1common_1_1config_1_1CliConfigParser.html", "classkcenon_1_1common_1_1config_1_1CliConfigParser" ],
          [ "config_change_event", "structkcenon_1_1common_1_1config_1_1config__change__event.html", "structkcenon_1_1common_1_1config_1_1config__change__event" ],
          [ "config_entry", "structkcenon_1_1common_1_1config_1_1config__entry.html", "structkcenon_1_1common_1_1config_1_1config__entry" ],
          [ "config_loader", "classkcenon_1_1common_1_1config_1_1config__loader.html", "classkcenon_1_1common_1_1config_1_1config__loader" ],
          [ "config_snapshot", "structkcenon_1_1common_1_1config_1_1config__snapshot.html", "structkcenon_1_1common_1_1config_1_1config__snapshot" ],
          [ "config_watcher", "classkcenon_1_1common_1_1config_1_1config__watcher.html", "classkcenon_1_1common_1_1config_1_1config__watcher" ],
          [ "database_config", "structkcenon_1_1common_1_1config_1_1database__config.html", "structkcenon_1_1common_1_1config_1_1database__config" ],
          [ "feature_flags", "structkcenon_1_1common_1_1config_1_1feature__flags.html", "structkcenon_1_1common_1_1config_1_1feature__flags" ],
          [ "field_metadata", "structkcenon_1_1common_1_1config_1_1field__metadata.html", "structkcenon_1_1common_1_1config_1_1field__metadata" ],
          [ "IConfigLoader", "classkcenon_1_1common_1_1config_1_1IConfigLoader.html", "classkcenon_1_1common_1_1config_1_1IConfigLoader" ],
          [ "logger_config", "structkcenon_1_1common_1_1config_1_1logger__config.html", "structkcenon_1_1common_1_1config_1_1logger__config" ],
          [ "monitoring_config", "structkcenon_1_1common_1_1config_1_1monitoring__config.html", "structkcenon_1_1common_1_1config_1_1monitoring__config" ],
          [ "network_config", "structkcenon_1_1common_1_1config_1_1network__config.html", "structkcenon_1_1common_1_1config_1_1network__config" ],
          [ "parsed_args", "structkcenon_1_1common_1_1config_1_1parsed__args.html", "structkcenon_1_1common_1_1config_1_1parsed__args" ],
          [ "pool_config", "structkcenon_1_1common_1_1config_1_1pool__config.html", "structkcenon_1_1common_1_1config_1_1pool__config" ],
          [ "thread_config", "structkcenon_1_1common_1_1config_1_1thread__config.html", "structkcenon_1_1common_1_1config_1_1thread__config" ],
          [ "tls_config", "structkcenon_1_1common_1_1config_1_1tls__config.html", "structkcenon_1_1common_1_1config_1_1tls__config" ],
          [ "tracing_config", "structkcenon_1_1common_1_1config_1_1tracing__config.html", "structkcenon_1_1common_1_1config_1_1tracing__config" ],
          [ "unified_config", "structkcenon_1_1common_1_1config_1_1unified__config.html", "structkcenon_1_1common_1_1config_1_1unified__config" ],
          [ "validation_issue", "structkcenon_1_1common_1_1config_1_1validation__issue.html", "structkcenon_1_1common_1_1config_1_1validation__issue" ]
        ] ],
        [ "detail", "namespacekcenon_1_1common_1_1detail.html", [
          [ "event_type_id", "structkcenon_1_1common_1_1detail_1_1event__type__id.html", "structkcenon_1_1common_1_1detail_1_1event__type__id" ]
        ] ],
        [ "di", "namespacekcenon_1_1common_1_1di.html", [
          [ "bootstrapper_options", "structkcenon_1_1common_1_1di_1_1bootstrapper__options.html", "structkcenon_1_1common_1_1di_1_1bootstrapper__options" ],
          [ "IBootstrapper", "classkcenon_1_1common_1_1di_1_1IBootstrapper.html", "classkcenon_1_1common_1_1di_1_1IBootstrapper" ],
          [ "IServiceContainer", "classkcenon_1_1common_1_1di_1_1IServiceContainer.html", "classkcenon_1_1common_1_1di_1_1IServiceContainer" ],
          [ "IServiceScope", "classkcenon_1_1common_1_1di_1_1IServiceScope.html", "classkcenon_1_1common_1_1di_1_1IServiceScope" ],
          [ "service_container", "classkcenon_1_1common_1_1di_1_1service__container.html", "classkcenon_1_1common_1_1di_1_1service__container" ],
          [ "service_descriptor", "structkcenon_1_1common_1_1di_1_1service__descriptor.html", "structkcenon_1_1common_1_1di_1_1service__descriptor" ],
          [ "service_scope", "classkcenon_1_1common_1_1di_1_1service__scope.html", "classkcenon_1_1common_1_1di_1_1service__scope" ],
          [ "ServiceContainer", "classkcenon_1_1common_1_1di_1_1ServiceContainer.html", "classkcenon_1_1common_1_1di_1_1ServiceContainer" ],
          [ "unified_bootstrapper", "classkcenon_1_1common_1_1di_1_1unified__bootstrapper.html", "classkcenon_1_1common_1_1di_1_1unified__bootstrapper" ]
        ] ],
        [ "events", "namespacekcenon_1_1common_1_1events.html", [
          [ "error_event", "structkcenon_1_1common_1_1events_1_1error__event.html", "structkcenon_1_1common_1_1events_1_1error__event" ],
          [ "metric_event", "structkcenon_1_1common_1_1events_1_1metric__event.html", "structkcenon_1_1common_1_1events_1_1metric__event" ],
          [ "module_started_event", "structkcenon_1_1common_1_1events_1_1module__started__event.html", "structkcenon_1_1common_1_1events_1_1module__started__event" ],
          [ "module_stopped_event", "structkcenon_1_1common_1_1events_1_1module__stopped__event.html", "structkcenon_1_1common_1_1events_1_1module__stopped__event" ]
        ] ],
        [ "interfaces", "namespacekcenon_1_1common_1_1interfaces.html", [
          [ "composite_health_check", "classkcenon_1_1common_1_1interfaces_1_1composite__health__check.html", "classkcenon_1_1common_1_1interfaces_1_1composite__health__check" ],
          [ "GlobalLoggerRegistry", "classkcenon_1_1common_1_1interfaces_1_1GlobalLoggerRegistry.html", "classkcenon_1_1common_1_1interfaces_1_1GlobalLoggerRegistry" ],
          [ "health_check", "classkcenon_1_1common_1_1interfaces_1_1health__check.html", "classkcenon_1_1common_1_1interfaces_1_1health__check" ],
          [ "health_check_builder", "classkcenon_1_1common_1_1interfaces_1_1health__check__builder.html", "classkcenon_1_1common_1_1interfaces_1_1health__check__builder" ],
          [ "health_check_result", "structkcenon_1_1common_1_1interfaces_1_1health__check__result.html", "structkcenon_1_1common_1_1interfaces_1_1health__check__result" ],
          [ "health_dependency_graph", "classkcenon_1_1common_1_1interfaces_1_1health__dependency__graph.html", "classkcenon_1_1common_1_1interfaces_1_1health__dependency__graph" ],
          [ "health_monitor", "classkcenon_1_1common_1_1interfaces_1_1health__monitor.html", "classkcenon_1_1common_1_1interfaces_1_1health__monitor" ],
          [ "health_monitor_stats", "structkcenon_1_1common_1_1interfaces_1_1health__monitor__stats.html", "structkcenon_1_1common_1_1interfaces_1_1health__monitor__stats" ],
          [ "http_request", "structkcenon_1_1common_1_1interfaces_1_1http__request.html", "structkcenon_1_1common_1_1interfaces_1_1http__request" ],
          [ "http_response", "structkcenon_1_1common_1_1interfaces_1_1http__response.html", "structkcenon_1_1common_1_1interfaces_1_1http__response" ],
          [ "IDatabase", "classkcenon_1_1common_1_1interfaces_1_1IDatabase.html", "classkcenon_1_1common_1_1interfaces_1_1IDatabase" ],
          [ "IExecutor", "classkcenon_1_1common_1_1interfaces_1_1IExecutor.html", "classkcenon_1_1common_1_1interfaces_1_1IExecutor" ],
          [ "IExecutorProvider", "classkcenon_1_1common_1_1interfaces_1_1IExecutorProvider.html", "classkcenon_1_1common_1_1interfaces_1_1IExecutorProvider" ],
          [ "IHttpClient", "classkcenon_1_1common_1_1interfaces_1_1IHttpClient.html", "classkcenon_1_1common_1_1interfaces_1_1IHttpClient" ],
          [ "IHttpClientProvider", "classkcenon_1_1common_1_1interfaces_1_1IHttpClientProvider.html", "classkcenon_1_1common_1_1interfaces_1_1IHttpClientProvider" ],
          [ "IJob", "classkcenon_1_1common_1_1interfaces_1_1IJob.html", "classkcenon_1_1common_1_1interfaces_1_1IJob" ],
          [ "ILogger", "classkcenon_1_1common_1_1interfaces_1_1ILogger.html", "classkcenon_1_1common_1_1interfaces_1_1ILogger" ],
          [ "ILoggerProvider", "classkcenon_1_1common_1_1interfaces_1_1ILoggerProvider.html", "classkcenon_1_1common_1_1interfaces_1_1ILoggerProvider" ],
          [ "ILoggerRegistry", "classkcenon_1_1common_1_1interfaces_1_1ILoggerRegistry.html", "classkcenon_1_1common_1_1interfaces_1_1ILoggerRegistry" ],
          [ "IMetricCollector", "classkcenon_1_1common_1_1interfaces_1_1IMetricCollector.html", "classkcenon_1_1common_1_1interfaces_1_1IMetricCollector" ],
          [ "IMetricCollectorProvider", "classkcenon_1_1common_1_1interfaces_1_1IMetricCollectorProvider.html", "classkcenon_1_1common_1_1interfaces_1_1IMetricCollectorProvider" ],
          [ "IMonitor", "classkcenon_1_1common_1_1interfaces_1_1IMonitor.html", "classkcenon_1_1common_1_1interfaces_1_1IMonitor" ],
          [ "IMonitorable", "classkcenon_1_1common_1_1interfaces_1_1IMonitorable.html", "classkcenon_1_1common_1_1interfaces_1_1IMonitorable" ],
          [ "IMonitorProvider", "classkcenon_1_1common_1_1interfaces_1_1IMonitorProvider.html", "classkcenon_1_1common_1_1interfaces_1_1IMonitorProvider" ],
          [ "IStats", "classkcenon_1_1common_1_1interfaces_1_1IStats.html", "classkcenon_1_1common_1_1interfaces_1_1IStats" ],
          [ "IThreadPool", "classkcenon_1_1common_1_1interfaces_1_1IThreadPool.html", "classkcenon_1_1common_1_1interfaces_1_1IThreadPool" ],
          [ "IThreadPoolProvider", "classkcenon_1_1common_1_1interfaces_1_1IThreadPoolProvider.html", "classkcenon_1_1common_1_1interfaces_1_1IThreadPoolProvider" ],
          [ "IUdpClient", "classkcenon_1_1common_1_1interfaces_1_1IUdpClient.html", "classkcenon_1_1common_1_1interfaces_1_1IUdpClient" ],
          [ "IUdpClientProvider", "classkcenon_1_1common_1_1interfaces_1_1IUdpClientProvider.html", "classkcenon_1_1common_1_1interfaces_1_1IUdpClientProvider" ],
          [ "lambda_health_check", "classkcenon_1_1common_1_1interfaces_1_1lambda__health__check.html", "classkcenon_1_1common_1_1interfaces_1_1lambda__health__check" ],
          [ "log_entry", "structkcenon_1_1common_1_1interfaces_1_1log__entry.html", "structkcenon_1_1common_1_1interfaces_1_1log__entry" ],
          [ "logger_config", "structkcenon_1_1common_1_1interfaces_1_1logger__config.html", "structkcenon_1_1common_1_1interfaces_1_1logger__config" ],
          [ "metric_value", "structkcenon_1_1common_1_1interfaces_1_1metric__value.html", "structkcenon_1_1common_1_1interfaces_1_1metric__value" ],
          [ "metrics_snapshot", "structkcenon_1_1common_1_1interfaces_1_1metrics__snapshot.html", "structkcenon_1_1common_1_1interfaces_1_1metrics__snapshot" ],
          [ "null_http_client", "classkcenon_1_1common_1_1interfaces_1_1null__http__client.html", "classkcenon_1_1common_1_1interfaces_1_1null__http__client" ],
          [ "null_metric_collector", "classkcenon_1_1common_1_1interfaces_1_1null__metric__collector.html", "classkcenon_1_1common_1_1interfaces_1_1null__metric__collector" ],
          [ "null_udp_client", "classkcenon_1_1common_1_1interfaces_1_1null__udp__client.html", "classkcenon_1_1common_1_1interfaces_1_1null__udp__client" ],
          [ "NullLogger", "classkcenon_1_1common_1_1interfaces_1_1NullLogger.html", "classkcenon_1_1common_1_1interfaces_1_1NullLogger" ],
          [ "registry_event", "structkcenon_1_1common_1_1interfaces_1_1registry__event.html", "structkcenon_1_1common_1_1interfaces_1_1registry__event" ],
          [ "RegistryAuditLog", "classkcenon_1_1common_1_1interfaces_1_1RegistryAuditLog.html", "classkcenon_1_1common_1_1interfaces_1_1RegistryAuditLog" ],
          [ "scoped_timer", "classkcenon_1_1common_1_1interfaces_1_1scoped__timer.html", "classkcenon_1_1common_1_1interfaces_1_1scoped__timer" ],
          [ "stats_snapshot", "structkcenon_1_1common_1_1interfaces_1_1stats__snapshot.html", "structkcenon_1_1common_1_1interfaces_1_1stats__snapshot" ],
          [ "system_metrics", "structkcenon_1_1common_1_1interfaces_1_1system__metrics.html", "structkcenon_1_1common_1_1interfaces_1_1system__metrics" ],
          [ "thread_pool_metrics", "structkcenon_1_1common_1_1interfaces_1_1thread__pool__metrics.html", "structkcenon_1_1common_1_1interfaces_1_1thread__pool__metrics" ],
          [ "udp_endpoint", "structkcenon_1_1common_1_1interfaces_1_1udp__endpoint.html", "structkcenon_1_1common_1_1interfaces_1_1udp__endpoint" ],
          [ "udp_send_options", "structkcenon_1_1common_1_1interfaces_1_1udp__send__options.html", "structkcenon_1_1common_1_1interfaces_1_1udp__send__options" ],
          [ "udp_statistics", "structkcenon_1_1common_1_1interfaces_1_1udp__statistics.html", "structkcenon_1_1common_1_1interfaces_1_1udp__statistics" ],
          [ "worker_metrics", "structkcenon_1_1common_1_1interfaces_1_1worker__metrics.html", "structkcenon_1_1common_1_1interfaces_1_1worker__metrics" ]
        ] ],
        [ "logging", "namespacekcenon_1_1common_1_1logging.html", [
          [ "ConsoleLogger", "classkcenon_1_1common_1_1logging_1_1ConsoleLogger.html", "classkcenon_1_1common_1_1logging_1_1ConsoleLogger" ]
        ] ],
        [ "patterns", "namespacekcenon_1_1common_1_1patterns.html", [
          [ "SimpleEventBus", "classkcenon_1_1common_1_1patterns_1_1SimpleEventBus.html", "classkcenon_1_1common_1_1patterns_1_1SimpleEventBus" ],
          [ "Singleton", "classkcenon_1_1common_1_1patterns_1_1Singleton.html", null ]
        ] ],
        [ "resilience", "namespacekcenon_1_1common_1_1resilience.html", [
          [ "circuit_breaker", "classkcenon_1_1common_1_1resilience_1_1circuit__breaker.html", "classkcenon_1_1common_1_1resilience_1_1circuit__breaker" ],
          [ "circuit_breaker_config", "structkcenon_1_1common_1_1resilience_1_1circuit__breaker__config.html", "structkcenon_1_1common_1_1resilience_1_1circuit__breaker__config" ],
          [ "failure_window", "classkcenon_1_1common_1_1resilience_1_1failure__window.html", "classkcenon_1_1common_1_1resilience_1_1failure__window" ]
        ] ],
        [ "utils", "namespacekcenon_1_1common_1_1utils.html", [
          [ "detail", "namespacekcenon_1_1common_1_1utils_1_1detail.html", [
            [ "RawDelete", "structkcenon_1_1common_1_1utils_1_1detail_1_1RawDelete.html", "structkcenon_1_1common_1_1utils_1_1detail_1_1RawDelete" ]
          ] ],
          [ "CircularBuffer", "classkcenon_1_1common_1_1utils_1_1CircularBuffer.html", "classkcenon_1_1common_1_1utils_1_1CircularBuffer" ],
          [ "ObjectPool", "classkcenon_1_1common_1_1utils_1_1ObjectPool.html", "classkcenon_1_1common_1_1utils_1_1ObjectPool" ],
          [ "PoolDeleter", "structkcenon_1_1common_1_1utils_1_1PoolDeleter.html", "structkcenon_1_1common_1_1utils_1_1PoolDeleter" ],
          [ "SPSCCircularBuffer", "classkcenon_1_1common_1_1utils_1_1SPSCCircularBuffer.html", "classkcenon_1_1common_1_1utils_1_1SPSCCircularBuffer" ]
        ] ],
        [ "common_error_category", "classkcenon_1_1common_1_1common__error__category.html", "classkcenon_1_1common_1_1common__error__category" ],
        [ "database_null", "structkcenon_1_1common_1_1database__null.html", null ],
        [ "enum_traits", "structkcenon_1_1common_1_1enum__traits.html", null ],
        [ "enum_traits< interfaces::health_check_type >", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1health__check__type_01_4.html", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1health__check__type_01_4" ],
        [ "enum_traits< interfaces::health_status >", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1health__status_01_4.html", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1health__status_01_4" ],
        [ "enum_traits< interfaces::log_level >", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1log__level_01_4.html", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1log__level_01_4" ],
        [ "enum_traits< interfaces::metric_type >", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1metric__type_01_4.html", "structkcenon_1_1common_1_1enum__traits_3_01interfaces_1_1metric__type_01_4" ],
        [ "error_category", "classkcenon_1_1common_1_1error__category.html", "classkcenon_1_1common_1_1error__category" ],
        [ "error_info", "structkcenon_1_1common_1_1error__info.html", "structkcenon_1_1common_1_1error__info" ],
        [ "event", "structkcenon_1_1common_1_1event.html", "structkcenon_1_1common_1_1event" ],
        [ "exception_mapper", "classkcenon_1_1common_1_1exception__mapper.html", "classkcenon_1_1common_1_1exception__mapper" ],
        [ "module_version", "structkcenon_1_1common_1_1module__version.html", "structkcenon_1_1common_1_1module__version" ],
        [ "Option", "classkcenon_1_1common_1_1Option.html", null ],
        [ "Optional", "classkcenon_1_1common_1_1Optional.html", "classkcenon_1_1common_1_1Optional" ],
        [ "Result", "classkcenon_1_1common_1_1Result.html", "classkcenon_1_1common_1_1Result" ],
        [ "simple_event_bus", "classkcenon_1_1common_1_1simple__event__bus.html", "classkcenon_1_1common_1_1simple__event__bus" ],
        [ "source_location", "structkcenon_1_1common_1_1source__location.html", "structkcenon_1_1common_1_1source__location" ],
        [ "typed_error_code", "classkcenon_1_1common_1_1typed__error__code.html", "classkcenon_1_1common_1_1typed__error__code" ],
        [ "version_info", "structkcenon_1_1common_1_1version__info.html", "structkcenon_1_1common_1_1version__info" ]
      ] ]
    ] ],
    [ "app_liveness_check", "classapp__liveness__check.html", "classapp__liveness__check" ],
    [ "cache_readiness_check", "classcache__readiness__check.html", "classcache__readiness__check" ],
    [ "calculation_job", "classcalculation__job.html", "classcalculation__job" ],
    [ "Connection", "structConnection.html", "structConnection" ],
    [ "database_dependency_check", "classdatabase__dependency__check.html", "classdatabase__dependency__check" ],
    [ "DataService", "classDataService.html", "classDataService" ],
    [ "example_executor_provider", "classexample__executor__provider.html", "classexample__executor__provider" ],
    [ "FriendlyGreeter", "classFriendlyGreeter.html", "classFriendlyGreeter" ],
    [ "function_job", "classfunction__job.html", "classfunction__job" ],
    [ "ICounter", "classICounter.html", "classICounter" ],
    [ "IGreeter", "classIGreeter.html", "classIGreeter" ],
    [ "mock_executor", "classmock__executor.html", "classmock__executor" ],
    [ "order_placed", "structorder__placed.html", "structorder__placed" ],
    [ "SequentialCounter", "classSequentialCounter.html", "classSequentialCounter" ],
    [ "system_alert", "structsystem__alert.html", "structsystem__alert" ],
    [ "User", "structUser.html", "structUser" ],
    [ "user_logged_in", "structuser__logged__in.html", "structuser__logged__in" ]
];