Common System: examples/circuit_breaker_example.cpp File Reference
circuit_breaker_example.cpp File Reference
#include <kcenon/common/resilience/circuit_breaker.h>
#include <chrono>
#include <iostream>
#include <string>
#include <thread>
Functions
std::string state_name (circuit_state s)
bool call_external_service (bool should_fail)
int main ()
Function Documentation
call_external_service()
bool call_external_service (bool should_fail)
Examples
circuit_breaker_example.cpp.
Definition at line 41 of file circuit_breaker_example.cpp.
{
    if (should_fail)
    {
        throw std::runtime_error("Service unavailable");
    }
    return true;
}
Referenced by main().
main()
int main ()
Definition at line 50 of file circuit_breaker_example.cpp.
{
    std::cout << "=== Circuit Breaker Example ===\n\n";
    // Configure: open after 3 failures, 1-second timeout
    circuit_breaker_config config;
    config.failure_threshold = 3;
    config.success_threshold = 2;
    config.timeout = std::chrono::seconds(1);
    circuit_breaker breaker(config);
    std::cout << "Initial state: " << state_name(breaker.get_state()) << "\n\n";
    // Phase 1: Simulate failures to trip the breaker
    std::cout << "1. Simulating failures...\n";
    for (int i = 0; i < 4; ++i)
    {
        if (!breaker.allow_request())
        {
            std::cout << "   Request " << i << ": REJECTED (circuit open)\n";
            continue;
        }
        try
        {
            auto guard = breaker.make_guard();
            call_external_service(true); // Will fail
            guard.record_success();
        }
        catch (const std::exception& e)
        {
            std::cout << "   Request " << i << ": FAILED (" << e.what() << ")\n";
        }
        std::cout << "   State: " << state_name(breaker.get_state()) << "\n";
    }
    // Phase 2: Wait for timeout and try again
    std::cout << "\n2. Waiting for timeout (1s)...\n";
    std::this_thread::sleep_for(std::chrono::milliseconds(1100));
    std::cout << "   State after timeout: " << state_name(breaker.get_state()) << "\n";
    // Phase 3: Recover with successful requests
    std::cout << "\n3. Recovering with successful requests...\n";
    for (int i = 0; i < 3; ++i)
    {
        if (!breaker.allow_request())
        {
            std::cout << "   Recovery " << i << ": REJECTED\n";
            continue;
        }
        auto guard = breaker.make_guard();
        call_external_service(false); // Success
        guard.record_success();
        std::cout << "   Recovery " << i << ": SUCCESS, state=" << state_name(breaker.get_state())
                  << "\n";
    }
    // Phase 4: Show stats
    std::cout << "\n4. Circuit breaker stats:\n";
    auto stats = breaker.get_stats();
    for (auto it = stats.begin(); it != stats.end(); ++it)
    {
        const auto& name = it->first;
        const auto& val = it->second;
        std::visit(
            [&name](const auto& v) { std::cout << "   " << name << ": " << v << "\n"; },
            val);
    }
    std::cout << "\nDone.\n";
    return 0;
}
References kcenon::common::resilience::circuit_breaker::allow_request(), call_external_service(), kcenon::common::resilience::circuit_breaker_config::failure_threshold, kcenon::common::resilience::circuit_breaker::get_state(), kcenon::common::resilience::circuit_breaker::get_stats(), kcenon::common::resilience::circuit_breaker::make_guard(), state_name(), kcenon::common::resilience::circuit_breaker_config::success_threshold, and kcenon::common::resilience::circuit_breaker_config::timeout.
state_name()
std::string state_name (circuit_state s)
Examples
circuit_breaker_example.cpp.
Definition at line 25 of file circuit_breaker_example.cpp.
{
    switch (s)
    {
    case circuit_state::CLOSED:
        return "CLOSED";
    case circuit_state::OPEN:
        return "OPEN";
    case circuit_state::HALF_OPEN:
        return "HALF_OPEN";
    default:
        return "UNKNOWN";
    }
}
Referenced by main().