Common System: kcenon::common::Result< T > Class Template Reference
kcenon::common::Result< T > Class Template Reference export
module kcenon.common
Result type for error handling with member function support.
#include <core.h>
Public Types
using value_type = T
Type alias for the contained value type (for concept compatibility)
using error_type = error_info
Type alias for the error type.
Public Member Functions
Result (const T &value)
Result (T &&value)
Result (const error_info &error)
Result (error_info &&error)
Result (const typed_error_code &ec)
Construct from category-based typed_error_code.
Result ()=delete
Default constructor is deleted to enforce explicit initialization.
Result (const Result &)=default
Result (Result &&)=default
Result & operator= (const Result &)=default
Result & operator= (Result &&)=default
bool is_ok () const
Check if result contains a successful value.
bool is_err () const
Check if result contains an error.
const T & unwrap () const
Get value from result (throws if error)
T & unwrap ()
Get mutable value from result (throws if error)
T unwrap_or (T default_value) const
Get value or return default.
T value_or (T default_value) const
Get value or return default (C++23 std::expected compatible)
const T & value () const
Get value reference (const)
T & value ()
Get value reference (mutable)
const error_info & error () const
Get error reference.
template<typename F >
auto map (F &&func) const -> Result< decltype(func(std::declval< T >()))>
Map a function over a successful result.
template<typename F >
auto and_then (F &&func) const -> decltype(func(std::declval< T >()))
Map a function that returns a Result (flatMap/bind)
template<typename F >
Result< T > or_else (F &&func) const
Provide alternative value if error.
Result (const T &value)
Result (T &&value)
Result (const error_info &error)
Result (error_info &&error)
Result ()=delete
Result (const Result &)=default
Result (Result &&)=default
Result & operator= (const Result &)=default
Result & operator= (Result &&)=default
bool is_ok () const
bool is_err () const
const T & unwrap () const
T & unwrap ()
T unwrap_or (T default_value) const
T value_or (T default_value) const
const T & value () const
T & value ()
const error_info & error () const
template<typename F >
auto map (F &&func) const -> Result< decltype(func(std::declval< T >()))>
template<typename F >
auto and_then (F &&func) const -> decltype(func(std::declval< T >()))
template<typename F >
Result< T > or_else (F &&func) const
Static Public Member Functions
template<typename U = T>
static Result< T > ok (U &&value)
Create a successful result with value (static factory)
static Result< T > err (const error_info &error)
Create an error result from error_info (static factory)
static Result< T > err (error_info &&error)
Create an error result from error_info (static factory, move)
static Result< T > err (int code, const std::string &message, const std::string &module="")
Create an error result with code and message (static factory)
static Result< T > err (const typed_error_code &ec)
Create an error result from category-based typed_error_code (static factory)
static Result< T > uninitialized ()
Create an explicitly uninitialized result (use with caution)
template<typename U = T>
static Result< T > ok (U &&value)
static Result< T > err (const error_info &error)
static Result< T > err (error_info &&error)
static Result< T > err (int code, const std::string &message, const std::string &module="")
static Result< T > uninitialized ()
Private Attributes
std::optional< T > value_
std::optional< error_info > error_
Detailed Description
template<typename T>
class kcenon::common::Result< T >
Result type for error handling with member function support.
A Result<T> can be in one of two states:
Ok - Contains a valid value of type T
Error - Contains an error_info describing the failure
This provides a type-safe way to handle errors without exceptions.
IMPORTANT: Default-constructed Results are deleted to enforce explicit initialization. For explicit construction, use factory methods Result<T>::ok() and Result<T>::err().
Thread Safety Note:
Based on std::optional, which is NOT thread-safe for concurrent access.
Safe to pass by value or const reference across threads.
Concurrent reads of the same Result are safe if guaranteed no writes.
For shared mutable access, wrap in std::mutex or similar.
A Result<T> can be in one of two states:
Ok - Contains a valid value of type T
Error - Contains an error_info describing the failure
Template Parameters
T The type of the successful value
Examples
concepts_showcase_example.cpp, executor_example.cpp, multi_system_app/main.cpp, result_example.cpp, and unwrap_demo.cpp.
Definition at line 165 of file core.cppm.
Member Typedef Documentation
error_type
template<typename T > typedef error_info kcenon::common::Result< T >::error_type = error_info export
Type alias for the error type.
Definition at line 172 of file core.h.
value_type
template<typename T > typedef T kcenon::common::Result< T >::value_type = T export
Type alias for the contained value type (for concept compatibility)
Definition at line 169 of file core.h.
Constructor & Destructor Documentation
Result() [1/15]
template<typename T > kcenon::common::Result< T >::Result (const T & value) inline
Definition at line 182 of file core.h.
: value_(value), error_(std::nullopt) {}
Result() [2/15]
template<typename T > kcenon::common::Result< T >::Result (T && value) inline
Definition at line 183 of file core.h.
: value_(std::move(value)), error_(std::nullopt) {}
Result() [3/15]
template<typename T > kcenon::common::Result< T >::Result (const error_info & error) inline
Definition at line 184 of file core.h.
: value_(std::nullopt), error_(error) {}
Result() [4/15]
template<typename T > kcenon::common::Result< T >::Result (error_info && error) inline
Definition at line 185 of file core.h.
: value_(std::nullopt), error_(std::move(error)) {}
Result() [5/15]
template<typename T > kcenon::common::Result< T >::Result (const typed_error_code & ec) inline
Construct from category-based typed_error_code.
Enables seamless integration with the decentralized error category system. The typed_error_code is converted to error_info internally.
Parameters
ec Category-based typed error code
Definition at line 195 of file core.h.
: value_(std::nullopt), error_(error_info(ec)) {}
Result() [6/15]
template<typename T > kcenon::common::Result< T >::Result () delete
Default constructor is deleted to enforce explicit initialization.
This forces developers to explicitly use factory methods.
Migration: Use Result<T>::ok() for successful results or Result<T>::err() for error results. For cases requiring a default error state, use Result<T>::uninitialized() factory method.
Referenced by kcenon::common::Result< T >::err(), kcenon::common::Result< T >::err(), kcenon::common::Result< T >::err(), kcenon::common::Result< T >::err(), kcenon::common::Result< T >::map(), kcenon::common::Result< T >::ok(), and kcenon::common::Result< T >::uninitialized().
Result() [7/15]
template<typename T > kcenon::common::Result< T >::Result (const Result< T > &) default
Result() [8/15]
template<typename T > kcenon::common::Result< T >::Result (Result< T > &&) default
Result() [9/15]
template<typename T > kcenon::common::Result< T >::Result (const T & value) inline export
Definition at line 175 of file core.cppm.
: value_(value), error_(std::nullopt) {}
Result() [10/15]
template<typename T > kcenon::common::Result< T >::Result (T && value) inline export
Definition at line 176 of file core.cppm.
: value_(std::move(value)), error_(std::nullopt) {}
Result() [11/15]
template<typename T > kcenon::common::Result< T >::Result (const error_info & error) inline export
Definition at line 177 of file core.cppm.
: value_(std::nullopt), error_(error) {}
Result() [12/15]
template<typename T > kcenon::common::Result< T >::Result (error_info && error) inline export
Definition at line 178 of file core.cppm.
: value_(std::nullopt), error_(std::move(error)) {}
Result() [13/15]
template<typename T > kcenon::common::Result< T >::Result () export delete
Result() [14/15]
template<typename T > kcenon::common::Result< T >::Result (const Result< T > &) export default
Result() [15/15]
template<typename T > kcenon::common::Result< T >::Result (Result< T > &&) export default
Member Function Documentation
and_then() [1/2]
template<typename T > template<typename F > auto kcenon::common::Result< T >::and_then (F && func) const -> decltype(func(std::declval<T>())) inline
Map a function that returns a Result (flatMap/bind)
Definition at line 430 of file core.h.
{
        using ReturnType = decltype(func(std::declval<T>()));
        if (is_ok()) {
            return func(value_.value());
        } else if (is_err()) {
            return ReturnType(error_.value());
        } else {
            // Uninitialized state - use uninitialized factory
            return ReturnType::uninitialized();
        }
    }
References kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), kcenon::common::Result< T >::is_ok(), and kcenon::common::Result< T >::value_.
and_then() [2/2]
template<typename T > template<typename F > auto kcenon::common::Result< T >::and_then (F && func) const -> decltype(func(std::declval<T>())) inline export
Definition at line 306 of file core.cppm.
{
        using ReturnType = decltype(func(std::declval<T>()));
        if (is_ok()) {
            return func(value_.value());
        } else if (is_err()) {
            return ReturnType(error_.value());
        } else {
            return ReturnType::uninitialized();
        }
    }
References kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), kcenon::common::Result< T >::is_ok(), and kcenon::common::Result< T >::value_.
err() [1/7]
template<typename T > static Result< T > kcenon::common::Result< T >::err (const error_info & error) inline static
Create an error result from error_info (static factory)
Parameters
error The error information
Returns
Result<T> containing the error
Definition at line 232 of file core.h.
{
        return Result<T>(error);
    }
References kcenon::common::Result< T >::error(), and kcenon::common::Result< T >::Result().
Referenced by kcenon::common::enum_from_string(), kcenon::common::Result< T >::unwrap(), and kcenon::common::Result< T >::unwrap().
err() [2/7]
template<typename T > static Result< T > kcenon::common::Result< T >::err (const error_info & error) inline static export
Definition at line 193 of file core.cppm.
{
        return Result<T>(error);
    }
References kcenon::common::Result< T >::error(), and kcenon::common::Result< T >::Result().
err() [3/7]
template<typename T > static Result< T > kcenon::common::Result< T >::err (const typed_error_code & ec) inline static
Create an error result from category-based typed_error_code (static factory)
Enables seamless integration with the decentralized error category system.
Parameters
ec Category-based typed error code
Returns
Result<T> containing the error
Example usage:
Result<int> result = Result<int>::err(
    make_typed_error_code(common_error_category::not_found)
);
Definition at line 271 of file core.h.
{
        return Result<T>(ec);
    }
References kcenon::common::Result< T >::Result().
err() [4/7]
template<typename T > static Result< T > kcenon::common::Result< T >::err (error_info && error) inline static
Create an error result from error_info (static factory, move)
Parameters
error The error information
Returns
Result<T> containing the error
Definition at line 241 of file core.h.
{
        return Result<T>(std::move(error));
    }
References kcenon::common::Result< T >::error(), and kcenon::common::Result< T >::Result().
err() [5/7]
template<typename T > static Result< T > kcenon::common::Result< T >::err (error_info && error) inline static export
Definition at line 197 of file core.cppm.
{
        return Result<T>(std::move(error));
    }
References kcenon::common::Result< T >::error(), and kcenon::common::Result< T >::Result().
err() [6/7]
template<typename T > static Result< T > kcenon::common::Result< T >::err (int code, const std::string & message, const std::string & module = "") inline static
Create an error result with code and message (static factory)
Parameters
code Error code
message Error message
module Optional module name
Returns
Result<T> containing the error
Definition at line 252 of file core.h.
{
        return Result<T>(error_info{code, message, module});
    }
References kcenon::common::Result< T >::Result().
err() [7/7]
template<typename T > static Result< T > kcenon::common::Result< T >::err (int code, const std::string & message, const std::string & module = "") inline static export
Definition at line 201 of file core.cppm.
{
        return Result<T>(error_info{code, message, module});
    }
References kcenon::common::Result< T >::Result().
error() [1/2]
template<typename T > const error_info & kcenon::common::Result< T >::error () const inline
Get error reference.
Examples
executor_example.cpp, and result_example.cpp.
Definition at line 405 of file core.h.
{
        return error_.value();
    }
References kcenon::common::Result< T >::error_.
Referenced by kcenon::common::Result< T >::err(), kcenon::common::Result< T >::err(), mock_executor::execute(), mock_executor::execute_delayed(), and main().
error() [2/2]
template<typename T > const error_info & kcenon::common::Result< T >::error () const inline export
Definition at line 288 of file core.cppm.
{
        return error_.value();
    }
References kcenon::common::Result< T >::error_.
is_err() [1/2]
template<typename T > bool kcenon::common::Result< T >::is_err () const inline
Check if result contains an error.
Definition at line 297 of file core.h.
{
        return error_.has_value();
    }
References kcenon::common::Result< T >::error_.
Referenced by kcenon::common::Result< T >::and_then(), kcenon::common::Result< T >::map(), kcenon::common::Result< T >::or_else(), kcenon::common::Result< T >::unwrap(), and kcenon::common::Result< T >::unwrap().
is_err() [2/2]
template<typename T > bool kcenon::common::Result< T >::is_err () const inline export
Definition at line 213 of file core.cppm.
{
        return error_.has_value();
    }
References kcenon::common::Result< T >::error_.
is_ok() [1/2]
template<typename T > bool kcenon::common::Result< T >::is_ok () const inline
Check if result contains a successful value.
Definition at line 290 of file core.h.
                       {
        return value_.has_value();
    }
References kcenon::common::Result< T >::value_.
Referenced by kcenon::common::Result< T >::and_then(), kcenon::common::Result< T >::map(), kcenon::common::Result< T >::or_else(), and kcenon::common::Result< T >::unwrap_or().
is_ok() [2/2]
template<typename T > bool kcenon::common::Result< T >::is_ok () const inline export
Definition at line 209 of file core.cppm.
                       {
        return value_.has_value();
    }
References kcenon::common::Result< T >::value_.
map() [1/2]
template<typename T > template<typename F > auto kcenon::common::Result< T >::map (F && func) const -> Result<decltype(func(std::declval<T>()))> inline
Map a function over a successful result.
Definition at line 413 of file core.h.
{
        using ReturnType = decltype(func(std::declval<T>()));
        if (is_ok()) {
            return Result<ReturnType>(func(value_.value()));
        } else if (is_err()) {
            return Result<ReturnType>(error_.value());
        } else {
            // Uninitialized state - use uninitialized factory
            return Result<ReturnType>::uninitialized();
        }
    }
References kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), kcenon::common::Result< T >::is_ok(), kcenon::common::Result< T >::Result(), kcenon::common::Result< T >::uninitialized(), and kcenon::common::Result< T >::value_.
map() [2/2]
template<typename T > template<typename F > auto kcenon::common::Result< T >::map (F && func) const -> Result<decltype(func(std::declval<T>()))> inline export
Definition at line 293 of file core.cppm.
{
        using ReturnType = decltype(func(std::declval<T>()));
        if (is_ok()) {
            return Result<ReturnType>(func(value_.value()));
        } else if (is_err()) {
            return Result<ReturnType>(error_.value());
        } else {
            return Result<ReturnType>::uninitialized();
        }
    }
References kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), kcenon::common::Result< T >::is_ok(), kcenon::common::Result< T >::Result(), kcenon::common::Result< T >::uninitialized(), and kcenon::common::Result< T >::value_.
ok() [1/2]
template<typename T > template<typename U = T> static Result< T > kcenon::common::Result< T >::ok (U && value) inline static
Create a successful result with value (static factory)
Parameters
value The value to wrap in Result (forwarded)
Returns
Result<T> containing the value
Uses perfect forwarding to avoid ambiguity and support both lvalues and rvalues efficiently.
Definition at line 223 of file core.h.
{
        return Result<T>(std::forward<U>(value));
    }
References kcenon::common::Result< T >::Result(), and kcenon::common::Result< T >::value().
Referenced by kcenon::common::config::cli_config_parser::apply_override(), kcenon::common::di::service_container::check_already_registered(), kcenon::common::di::service_container::check_frozen_for_registration(), kcenon::common::di::service_container::clear(), kcenon::common::di::service_scope::clear(), kcenon::common::config::config_watcher::do_reload(), kcenon::common::enum_from_string(), kcenon::common::interfaces::NullLogger::flush(), kcenon::common::bootstrap::SystemBootstrapper::initialize(), kcenon::common::di::unified_bootstrapper::initialize(), kcenon::common::config::config_loader::load_from_env(), kcenon::common::config::config_loader::load_from_string(), kcenon::common::config::cli_config_parser::load_with_cli_overrides(), kcenon::common::interfaces::NullLogger::log(), kcenon::common::interfaces::NullLogger::log(), kcenon::common::interfaces::NullLogger::log(), kcenon::common::logging::log(), kcenon::common::logging::log(), kcenon::common::logging::log(), kcenon::common::config::config_loader::merge_env_overrides(), kcenon::common::config::cli_config_parser::parse(), kcenon::common::di::unified_bootstrapper::register_core_services(), kcenon::common::interfaces::GlobalLoggerRegistry::register_factory(), kcenon::common::di::service_container::register_factory_internal(), kcenon::common::di::service_container::register_instance_internal(), kcenon::common::interfaces::GlobalLoggerRegistry::register_logger(), kcenon::common::bootstrap::SystemBootstrapper::register_loggers(), kcenon::common::di::unified_bootstrapper::register_module(), kcenon::common::di::unified_bootstrapper::register_optional_services(), kcenon::common::di::unified_bootstrapper::register_shutdown_hook(), kcenon::common::config::config_watcher::rollback(), kcenon::common::interfaces::GlobalLoggerRegistry::set_default_factory(), kcenon::common::interfaces::GlobalLoggerRegistry::set_default_logger(), kcenon::common::interfaces::NullLogger::set_level(), kcenon::common::di::unified_bootstrapper::shutdown(), kcenon::common::config::config_watcher::start(), kcenon::common::di::service_container::unregister_internal(), kcenon::common::interfaces::GlobalLoggerRegistry::unregister_logger(), kcenon::common::di::unified_bootstrapper::unregister_module(), kcenon::common::di::unified_bootstrapper::unregister_shutdown_hook(), and kcenon::common::config::config_loader::validate().
ok() [2/2]
template<typename T > template<typename U = T> static Result< T > kcenon::common::Result< T >::ok (U && value) inline static export
Definition at line 189 of file core.cppm.
{
        return Result<T>(std::forward<U>(value));
    }
References kcenon::common::Result< T >::Result(), and kcenon::common::Result< T >::value().
operator=() [1/4]
template<typename T > Result & kcenon::common::Result< T >::operator= (const Result< T > &) default
operator=() [2/4]
template<typename T > Result & kcenon::common::Result< T >::operator= (const Result< T > &) export default
operator=() [3/4]
template<typename T > Result & kcenon::common::Result< T >::operator= (Result< T > &&) default
operator=() [4/4]
template<typename T > Result & kcenon::common::Result< T >::operator= (Result< T > &&) export default
or_else() [1/2]
template<typename T > template<typename F > Result< T > kcenon::common::Result< T >::or_else (F && func) const inline
Provide alternative value if error.
Definition at line 447 of file core.h.
{
        if (is_ok()) {
            return *this;
        } else if (is_err()) {
            return func(error_.value());
        } else {
            // Uninitialized state
            return *this;
        }
    }
References kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), and kcenon::common::Result< T >::is_ok().
or_else() [2/2]
template<typename T > template<typename F > Result< T > kcenon::common::Result< T >::or_else (F && func) const inline export
Definition at line 319 of file core.cppm.
{
        if (is_ok()) {
            return *this;
        } else if (is_err()) {
            return func(error_.value());
        } else {
            return *this;
        }
    }
References kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), and kcenon::common::Result< T >::is_ok().
uninitialized() [1/2]
template<typename T > static Result< T > kcenon::common::Result< T >::uninitialized () inline static
Create an explicitly uninitialized result (use with caution)
Returns
Result<T> containing an error state indicating uninitialized
This factory method is provided for cases where an uninitialized state is explicitly required (e.g., delayed initialization, placeholder values). Use sparingly and prefer explicit initialization with ok() or err().
Definition at line 283 of file core.h.
{
        return Result<T>(error_info{-6, "Result not initialized", "common::Result"});
    }
References kcenon::common::Result< T >::Result().
Referenced by kcenon::common::Result< T >::map().
uninitialized() [2/2]
template<typename T > static Result< T > kcenon::common::Result< T >::uninitialized () inline static export
Definition at line 205 of file core.cppm.
{
        return Result<T>(error_info{-6, "Result not initialized", "common::Result"});
    }
References kcenon::common::Result< T >::Result().
unwrap() [1/4]
template<typename T > T & kcenon::common::Result< T >::unwrap () inline
Get mutable value from result (throws if error)
Exceptions
std::runtime_error if result contains error
Note
When source_location is available, error messages include file/line info
Definition at line 360 of file core.h.
                {
        if (is_err()) {
            const auto& err = error_.value();
            throw std::runtime_error("Called unwrap on error: " + err.message);
        }
        return value_.value();
    }
References kcenon::common::Result< T >::err(), kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), and kcenon::common::Result< T >::value_.
unwrap() [2/4]
template<typename T > T & kcenon::common::Result< T >::unwrap () inline export
Definition at line 260 of file core.cppm.
                {
        if (is_err()) {
            const auto& err = error_.value();
            throw std::runtime_error("Called unwrap on error: " + err.message);
        }
        return value_.value();
    }
References kcenon::common::Result< T >::err(), kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), and kcenon::common::Result< T >::value_.
unwrap() [3/4]
template<typename T > const T & kcenon::common::Result< T >::unwrap () const inline
Get value from result (throws if error)
Exceptions
std::runtime_error if result contains error
Note
When source_location is available, error messages include file/line info
Definition at line 326 of file core.h.
{
        if (is_err()) {
            const auto& err = error_.value();
            throw std::runtime_error("Called unwrap on error: " + err.message);
        }
        return value_.value();
    }
References kcenon::common::Result< T >::err(), kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), and kcenon::common::Result< T >::value_.
unwrap() [4/4]
template<typename T > const T & kcenon::common::Result< T >::unwrap () const inline export
Definition at line 252 of file core.cppm.
{
        if (is_err()) {
            const auto& err = error_.value();
            throw std::runtime_error("Called unwrap on error: " + err.message);
        }
        return value_.value();
    }
References kcenon::common::Result< T >::err(), kcenon::common::Result< T >::error_, kcenon::common::Result< T >::is_err(), and kcenon::common::Result< T >::value_.
unwrap_or() [1/2]
template<typename T > T kcenon::common::Result< T >::unwrap_or (T default_value) const inline
Get value or return default.
Examples
concepts_showcase_example.cpp.
Definition at line 372 of file core.h.
{
        if (is_ok()) {
            return value_.value();
        }
        return default_value;
    }
References kcenon::common::Result< T >::is_ok(), and kcenon::common::Result< T >::value_.
Referenced by safe_unwrap(), and kcenon::common::Result< T >::value_or().
unwrap_or() [2/2]
template<typename T > T kcenon::common::Result< T >::unwrap_or (T default_value) const inline export
Definition at line 269 of file core.cppm.
{
        if (is_ok()) {
            return value_.value();
        }
        return default_value;
    }
References kcenon::common::Result< T >::is_ok(), and kcenon::common::Result< T >::value_.
value() [1/4]
template<typename T > T & kcenon::common::Result< T >::value () inline
Get value reference (mutable)
Definition at line 398 of file core.h.
               {
        return value_.value();
    }
References kcenon::common::Result< T >::value_.
value() [2/4]
template<typename T > T & kcenon::common::Result< T >::value () inline export
Definition at line 284 of file core.cppm.
               {
        return value_.value();
    }
References kcenon::common::Result< T >::value_.
value() [3/4]
template<typename T > const T & kcenon::common::Result< T >::value () const inline
Get value reference (const)
Definition at line 391 of file core.h.
{
        return value_.value();
    }
References kcenon::common::Result< T >::value_.
Referenced by kcenon::common::Result< T >::ok().
value() [4/4]
template<typename T > const T & kcenon::common::Result< T >::value () const inline export
Definition at line 280 of file core.cppm.
{
        return value_.value();
    }
References kcenon::common::Result< T >::value_.
value_or() [1/2]
template<typename T > T kcenon::common::Result< T >::value_or (T default_value) const inline
Get value or return default (C++23 std::expected compatible)
Alias for unwrap_or() that matches std::expected::value_or() API.
Definition at line 384 of file core.h.
{
        return unwrap_or(std::move(default_value));
    }
References kcenon::common::Result< T >::unwrap_or().
Referenced by kcenon::common::interfaces::health_monitor::~health_monitor().
value_or() [2/2]
template<typename T > T kcenon::common::Result< T >::value_or (T default_value) const inline export
Definition at line 276 of file core.cppm.
{
        return unwrap_or(std::move(default_value));
    }
References kcenon::common::Result< T >::unwrap_or().
Member Data Documentation
error_
template<typename T > std::optional< error_info > kcenon::common::Result< T >::error_ export private
Definition at line 178 of file core.h.
Referenced by kcenon::common::Result< T >::and_then(), kcenon::common::Result< T >::error(), kcenon::common::Result< T >::is_err(), kcenon::common::Result< T >::map(), kcenon::common::Result< T >::or_else(), kcenon::common::Result< T >::unwrap(), and kcenon::common::Result< T >::unwrap().
value_
template<typename T > std::optional< T > kcenon::common::Result< T >::value_ export private
Definition at line 177 of file core.h.
Referenced by kcenon::common::Result< T >::and_then(), kcenon::common::Result< T >::is_ok(), kcenon::common::Result< T >::map(), kcenon::common::Result< T >::unwrap(), kcenon::common::Result< T >::unwrap(), kcenon::common::Result< T >::unwrap_or(), kcenon::common::Result< T >::value(), and kcenon::common::Result< T >::value().
The documentation for this class was generated from the following files:
include/kcenon/common/forward.h
include/kcenon/common/patterns/result/core.h
src/modules/result/core.cppm