Common System: kcenon::common::utils::CircularBuffer< T, Capacity > Class Template Reference
kcenon::common::utils::CircularBuffer< T, Capacity > Class Template Reference export
module kcenon.common
Thread-safe fixed-size circular buffer.
#include <circular_buffer.h>
Public Member Functions
CircularBuffer ()=default
bool push (const T &value, bool overwrite=false)
bool push (T &&value, bool overwrite=false)
std::optional< T > pop ()
bool empty () const
bool full () const
std::size_t size () const
constexpr std::size_t capacity () const
CircularBuffer ()=default
bool push (const T &value, bool overwrite=false)
Push a value to the buffer.
bool push (T &&value, bool overwrite=false)
std::optional< T > pop ()
Pop a value from the buffer.
bool empty () const
bool full () const
std::size_t size () const
constexpr std::size_t capacity () const
Private Member Functions
void advance (std::size_t &index) noexcept
bool is_full_locked () const noexcept
std::optional< T > pop_locked ()
void advance (std::size_t &index) noexcept
bool is_full_locked () const noexcept
std::optional< T > pop_locked ()
Private Attributes
std::mutex mutex_
std::array< T, Capacity > buffer_ {}
std::size_t head_ {0}
std::size_t tail_ {0}
std::size_t size_ {0}
Detailed Description
template<typename T, std::size_t Capacity>
class kcenon::common::utils::CircularBuffer< T, Capacity >
Thread-safe fixed-size circular buffer.
Template Parameters
T Element type
Capacity Maximum number of elements
Examples
utility_containers_example.cpp.
Definition at line 100 of file utils.cppm.
Constructor & Destructor Documentation
CircularBuffer() [1/2]
template<typename T , std::size_t Capacity> kcenon::common::utils::CircularBuffer< T, Capacity >::CircularBuffer () default
CircularBuffer() [2/2]
template<typename T , std::size_t Capacity> kcenon::common::utils::CircularBuffer< T, Capacity >::CircularBuffer () export default
Member Function Documentation
advance() [1/2]
template<typename T , std::size_t Capacity> void kcenon::common::utils::CircularBuffer< T, Capacity >::advance (std::size_t & index) inline private noexcept
Definition at line 84 of file circular_buffer.h.
{
        index = (index + 1) % Capacity;
    }
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::push(), and kcenon::common::utils::CircularBuffer< T, Capacity >::push().
advance() [2/2]
template<typename T , std::size_t Capacity> void kcenon::common::utils::CircularBuffer< T, Capacity >::advance (std::size_t & index) inline export private noexcept
Definition at line 169 of file utils.cppm.
{
        index = (index + 1) % Capacity;
    }
capacity() [1/2]
template<typename T , std::size_t Capacity> std::size_t kcenon::common::utils::CircularBuffer< T, Capacity >::capacity () const inline nodiscard constexpr
Definition at line 79 of file circular_buffer.h.
{
        return Capacity;
    }
capacity() [2/2]
template<typename T , std::size_t Capacity> std::size_t kcenon::common::utils::CircularBuffer< T, Capacity >::capacity () const inline nodiscard constexpr export
Definition at line 164 of file utils.cppm.
{
        return Capacity;
    }
empty() [1/2]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::empty () const inline nodiscard
Examples
utility_containers_example.cpp.
Definition at line 64 of file circular_buffer.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return size_ == 0;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
Referenced by main().
empty() [2/2]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::empty () const inline nodiscard export
Definition at line 149 of file utils.cppm.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return size_ == 0;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
full() [1/2]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::full () const inline nodiscard
Examples
utility_containers_example.cpp.
Definition at line 69 of file circular_buffer.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return size_ == Capacity;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
Referenced by main().
full() [2/2]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::full () const inline nodiscard export
Definition at line 154 of file utils.cppm.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return size_ == Capacity;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
is_full_locked() [1/2]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::is_full_locked () const inline private noexcept
Definition at line 88 of file circular_buffer.h.
{
        return size_ == Capacity;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::push(), and kcenon::common::utils::CircularBuffer< T, Capacity >::push().
is_full_locked() [2/2]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::is_full_locked () const inline export private noexcept
Definition at line 173 of file utils.cppm.
{
        return size_ == Capacity;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
pop() [1/2]
template<typename T , std::size_t Capacity> std::optional< T > kcenon::common::utils::CircularBuffer< T, Capacity >::pop () inline nodiscard
Examples
utility_containers_example.cpp.
Definition at line 59 of file circular_buffer.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return pop_locked();
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked().
Referenced by main().
pop() [2/2]
template<typename T , std::size_t Capacity> std::optional< T > kcenon::common::utils::CircularBuffer< T, Capacity >::pop () inline nodiscard export
Pop a value from the buffer.
Returns
The oldest value, or nullopt if empty
Definition at line 144 of file utils.cppm.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return pop_locked();
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked().
pop_locked() [1/2]
template<typename T , std::size_t Capacity> std::optional< T > kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked () inline private
Definition at line 92 of file circular_buffer.h.
{
        if (size_ == 0) {
            return std::nullopt;
        }
        auto value = std::move(buffer_[head_]);
        advance(head_);
        --size_;
        return value;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::advance(), kcenon::common::utils::CircularBuffer< T, Capacity >::buffer_, kcenon::common::utils::CircularBuffer< T, Capacity >::head_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::pop(), kcenon::common::utils::CircularBuffer< T, Capacity >::push(), and kcenon::common::utils::CircularBuffer< T, Capacity >::push().
pop_locked() [2/2]
template<typename T , std::size_t Capacity> std::optional< T > kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked () inline export private
Definition at line 177 of file utils.cppm.
{
        if (size_ == 0) {
            return std::nullopt;
        }
        auto value = std::move(buffer_[head_]);
        advance(head_);
        --size_;
        return value;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::advance(), kcenon::common::utils::CircularBuffer< T, Capacity >::buffer_, kcenon::common::utils::CircularBuffer< T, Capacity >::head_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
push() [1/4]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::push (const T & value, bool overwrite = false) inline
Examples
utility_containers_example.cpp.
Definition at line 31 of file circular_buffer.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (is_full_locked() && !overwrite) {
            return false;
        }
        if (is_full_locked()) {
            pop_locked();
        }
        buffer_[tail_] = value;
        advance(tail_);
        ++size_;
        return true;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::advance(), kcenon::common::utils::CircularBuffer< T, Capacity >::buffer_, kcenon::common::utils::CircularBuffer< T, Capacity >::is_full_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::size_, and kcenon::common::utils::CircularBuffer< T, Capacity >::tail_.
Referenced by main().
push() [2/4]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::push (const T & value, bool overwrite = false) inline export
Push a value to the buffer.
Parameters
value Value to push
overwrite If true, overwrite oldest value when full
Returns
true if pushed successfully, false if full and overwrite is false
Definition at line 112 of file utils.cppm.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (is_full_locked() && !overwrite) {
            return false;
        }
        if (is_full_locked()) {
            pop_locked();
        }
        buffer_[tail_] = value;
        advance(tail_);
        ++size_;
        return true;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::advance(), kcenon::common::utils::CircularBuffer< T, Capacity >::buffer_, kcenon::common::utils::CircularBuffer< T, Capacity >::is_full_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::size_, and kcenon::common::utils::CircularBuffer< T, Capacity >::tail_.
push() [3/4]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::push (T && value, bool overwrite = false) inline
Definition at line 45 of file circular_buffer.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (is_full_locked() && !overwrite) {
            return false;
        }
        if (is_full_locked()) {
            pop_locked();
        }
        buffer_[tail_] = std::move(value);
        advance(tail_);
        ++size_;
        return true;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::advance(), kcenon::common::utils::CircularBuffer< T, Capacity >::buffer_, kcenon::common::utils::CircularBuffer< T, Capacity >::is_full_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::size_, and kcenon::common::utils::CircularBuffer< T, Capacity >::tail_.
push() [4/4]
template<typename T , std::size_t Capacity> bool kcenon::common::utils::CircularBuffer< T, Capacity >::push (T && value, bool overwrite = false) inline export
Definition at line 126 of file utils.cppm.
{
        std::lock_guard<std::mutex> lock(mutex_);
        if (is_full_locked() && !overwrite) {
            return false;
        }
        if (is_full_locked()) {
            pop_locked();
        }
        buffer_[tail_] = std::move(value);
        advance(tail_);
        ++size_;
        return true;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::advance(), kcenon::common::utils::CircularBuffer< T, Capacity >::buffer_, kcenon::common::utils::CircularBuffer< T, Capacity >::is_full_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::size_, and kcenon::common::utils::CircularBuffer< T, Capacity >::tail_.
size() [1/2]
template<typename T , std::size_t Capacity> std::size_t kcenon::common::utils::CircularBuffer< T, Capacity >::size () const inline nodiscard
Examples
utility_containers_example.cpp.
Definition at line 74 of file circular_buffer.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return size_;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
Referenced by main().
size() [2/2]
template<typename T , std::size_t Capacity> std::size_t kcenon::common::utils::CircularBuffer< T, Capacity >::size () const inline nodiscard export
Definition at line 159 of file utils.cppm.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return size_;
    }
References kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_, and kcenon::common::utils::CircularBuffer< T, Capacity >::size_.
Member Data Documentation
buffer_
template<typename T , std::size_t Capacity> std::array< T, Capacity > kcenon::common::utils::CircularBuffer< T, Capacity >::buffer_ {} export private
Definition at line 103 of file circular_buffer.h.
{};
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::push(), and kcenon::common::utils::CircularBuffer< T, Capacity >::push().
head_
template<typename T , std::size_t Capacity> std::size_t kcenon::common::utils::CircularBuffer< T, Capacity >::head_ {0} export private
Definition at line 104 of file circular_buffer.h.
{0};
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked().
mutex_
template<typename T , std::size_t Capacity> std::mutex kcenon::common::utils::CircularBuffer< T, Capacity >::mutex_ mutable export private
Definition at line 102 of file circular_buffer.h.
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::empty(), kcenon::common::utils::CircularBuffer< T, Capacity >::full(), kcenon::common::utils::CircularBuffer< T, Capacity >::pop(), kcenon::common::utils::CircularBuffer< T, Capacity >::push(), kcenon::common::utils::CircularBuffer< T, Capacity >::push(), and kcenon::common::utils::CircularBuffer< T, Capacity >::size().
size_
template<typename T , std::size_t Capacity> std::size_t kcenon::common::utils::CircularBuffer< T, Capacity >::size_ {0} export private
Definition at line 106 of file circular_buffer.h.
{0};
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::empty(), kcenon::common::utils::CircularBuffer< T, Capacity >::full(), kcenon::common::utils::CircularBuffer< T, Capacity >::is_full_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::pop_locked(), kcenon::common::utils::CircularBuffer< T, Capacity >::push(), kcenon::common::utils::CircularBuffer< T, Capacity >::push(), and kcenon::common::utils::CircularBuffer< T, Capacity >::size().
tail_
template<typename T , std::size_t Capacity> std::size_t kcenon::common::utils::CircularBuffer< T, Capacity >::tail_ {0} export private
Definition at line 105 of file circular_buffer.h.
{0};
Referenced by kcenon::common::utils::CircularBuffer< T, Capacity >::push(), and kcenon::common::utils::CircularBuffer< T, Capacity >::push().
The documentation for this class was generated from the following files:
include/kcenon/common/utils/circular_buffer.h
src/modules/utils.cppm