Common System: mock_executor Class Reference
mock_executor Class Reference
Public Member Functions
mock_executor (size_t num_workers=4)
~mock_executor ()
Result< std::future< void > > execute (std::unique_ptr< IJob > &&job) override
Execute a job with Result-based error handling.
Result< std::future< void > > execute_delayed (std::unique_ptr< IJob > &&job, std::chrono::milliseconds delay) override
Execute a job with delay.
size_t worker_count () const override
Get the number of worker threads.
bool is_running () const override
Check if the executor is running.
size_t pending_tasks () const override
Get the number of pending tasks.
void shutdown (bool wait_for_completion) override
Shutdown the executor gracefully.
Public Member Functions inherited from kcenon::common::interfaces::IExecutor
virtual ~IExecutor ()=default
virtual ~IExecutor ()=default
Private Member Functions
void work_loop ()
Private Attributes
size_t num_workers_
std::atomic< bool > running_
std::atomic< size_t > pending_count_ {0}
std::vector< std::thread > workers_
std::queue< std::function< void()> > tasks_
std::mutex queue_mutex_
std::condition_variable queue_cv_
Detailed Description
Simple mock executor for demonstration
Examples
executor_example.cpp.
Definition at line 34 of file executor_example.cpp.
Constructor & Destructor Documentation
mock_executor()
mock_executor::mock_executor (size_t num_workers = 4) inline
Examples
executor_example.cpp.
Definition at line 36 of file executor_example.cpp.
        : num_workers_(num_workers), running_(true) {
        // Start worker threads
        for (size_t i = 0; i < num_workers_; ++i) {
            workers_.emplace_back([this] { work_loop(); });
        }
    }
References num_workers_, work_loop(), and workers_.
~mock_executor()
mock_executor::~mock_executor () inline
Examples
executor_example.cpp.
Definition at line 44 of file executor_example.cpp.
                     {
        shutdown(true);
    }
References shutdown().
Member Function Documentation
execute()
Result< std::future< void > > mock_executor::execute (std::unique_ptr< IJob > && job) inline override virtual
Execute a job with Result-based error handling.
Parameters
job The job to execute
Returns
Result containing future or error
Job-based execution provides better control and testability
Implements kcenon::common::interfaces::IExecutor.
Examples
executor_example.cpp.
Definition at line 49 of file executor_example.cpp.
{
        if (!job) {
            return error_info(1, "Job is null", "mock_executor");
        }
        auto promise = std::make_shared<std::promise<void>>();
        auto future = promise->get_future();
        // Use shared_ptr to make lambda copy-constructible
        auto shared_job = std::shared_ptr<IJob>(std::move(job));
        {
            std::lock_guard<std::mutex> lock(queue_mutex_);
            tasks_.emplace([shared_job, promise]() {
                try {
                    auto result = shared_job->execute();
                    if (result.is_err()) {
                        const auto& err = result.error();
                        promise->set_exception(
                            std::make_exception_ptr(
                                std::runtime_error(err.message)));
                    } else {
                        promise->set_value();
                    }
                } catch (...) {
                    promise->set_exception(std::current_exception());
                }
            });
            pending_count_++;
        }
        queue_cv_.notify_one();
        return ok(std::move(future));
    }
References kcenon::common::err(), kcenon::common::Result< T >::error(), kcenon::common::ok(), pending_count_, queue_cv_, queue_mutex_, and tasks_.
Referenced by main().
execute_delayed()
Result< std::future< void > > mock_executor::execute_delayed (std::unique_ptr< IJob > && job, std::chrono::milliseconds delay) inline override virtual
Execute a job with delay.
Parameters
job The job to execute
delay The delay before execution
Returns
Result containing future or error
Implements kcenon::common::interfaces::IExecutor.
Examples
executor_example.cpp.
Definition at line 84 of file executor_example.cpp.
{
        if (!job) {
            return error_info(1, "Job is null", "mock_executor");
        }
        auto promise = std::make_shared<std::promise<void>>();
        auto future = promise->get_future();
        // Use shared_ptr to make lambda copy-constructible
        auto shared_job = std::shared_ptr<IJob>(std::move(job));
        {
            std::lock_guard<std::mutex> lock(queue_mutex_);
            tasks_.emplace([shared_job, promise, delay]() {
                std::this_thread::sleep_for(delay);
                try {
                    auto result = shared_job->execute();
                    if (result.is_err()) {
                        const auto& err = result.error();
                        promise->set_exception(
                            std::make_exception_ptr(
                                std::runtime_error(err.message)));
                    } else {
                        promise->set_value();
                    }
                } catch (...) {
                    promise->set_exception(std::current_exception());
                }
            });
            pending_count_++;
        }
        queue_cv_.notify_one();
        return ok(std::move(future));
    }
References kcenon::common::err(), kcenon::common::Result< T >::error(), kcenon::common::ok(), pending_count_, queue_cv_, queue_mutex_, and tasks_.
Referenced by main().
is_running()
bool mock_executor::is_running () const inline override virtual
Check if the executor is running.
Returns
true if running, false otherwise
Implements kcenon::common::interfaces::IExecutor.
Examples
executor_example.cpp.
Definition at line 126 of file executor_example.cpp.
{
        return running_;
    }
References running_.
Referenced by main().
pending_tasks()
size_t mock_executor::pending_tasks () const inline override virtual
Get the number of pending tasks.
Returns
Number of tasks waiting to be executed
Implements kcenon::common::interfaces::IExecutor.
Examples
executor_example.cpp.
Definition at line 130 of file executor_example.cpp.
{
        return pending_count_;
    }
References pending_count_.
Referenced by main().
shutdown()
void mock_executor::shutdown (bool wait_for_completion) inline override virtual
Shutdown the executor gracefully.
Parameters
wait_for_completion Wait for all pending tasks to complete
Implements kcenon::common::interfaces::IExecutor.
Examples
executor_example.cpp.
Definition at line 134 of file executor_example.cpp.
{
        if (!running_) return;
        if (wait_for_completion) {
            // Wait for all tasks to complete
            std::unique_lock<std::mutex> lock(queue_mutex_);
            queue_cv_.wait(lock, [this] { return tasks_.empty(); });
        }
        running_ = false;
        queue_cv_.notify_all();
        for (auto& worker : workers_) {
            if (worker.joinable()) {
                worker.join();
            }
        }
    }
References queue_cv_, queue_mutex_, running_, tasks_, and workers_.
Referenced by main(), and ~mock_executor().
work_loop()
void mock_executor::work_loop () inline private
Examples
executor_example.cpp.
Definition at line 154 of file executor_example.cpp.
                     {
        while (running_) {
            std::function<void()> task;
            {
                std::unique_lock<std::mutex> lock(queue_mutex_);
                queue_cv_.wait(lock, [this] {
                    return !tasks_.empty() || !running_;
                });
                if (!running_ && tasks_.empty()) {
                    break;
                }
                if (!tasks_.empty()) {
                    task = std::move(tasks_.front());
                    tasks_.pop();
                    pending_count_--;
                }
            }
            if (task) {
                task();
            }
        }
    }
References pending_count_, queue_cv_, queue_mutex_, running_, and tasks_.
Referenced by mock_executor().
worker_count()
size_t mock_executor::worker_count () const inline override virtual
Get the number of worker threads.
Returns
Number of available workers
Implements kcenon::common::interfaces::IExecutor.
Examples
executor_example.cpp.
Definition at line 122 of file executor_example.cpp.
{
        return num_workers_;
    }
References num_workers_.
Referenced by main().
Member Data Documentation
num_workers_
size_t mock_executor::num_workers_ private
Examples
executor_example.cpp.
Definition at line 181 of file executor_example.cpp.
Referenced by mock_executor(), and worker_count().
pending_count_
std::atomic<size_t> mock_executor::pending_count_ {0} private
Examples
executor_example.cpp.
Definition at line 183 of file executor_example.cpp.
{0};
Referenced by execute(), execute_delayed(), pending_tasks(), and work_loop().
queue_cv_
std::condition_variable mock_executor::queue_cv_ private
Examples
executor_example.cpp.
Definition at line 187 of file executor_example.cpp.
Referenced by execute(), execute_delayed(), shutdown(), and work_loop().
queue_mutex_
std::mutex mock_executor::queue_mutex_ private
Examples
executor_example.cpp.
Definition at line 186 of file executor_example.cpp.
Referenced by execute(), execute_delayed(), shutdown(), and work_loop().
running_
std::atomic<bool> mock_executor::running_ private
Examples
executor_example.cpp.
Definition at line 182 of file executor_example.cpp.
Referenced by is_running(), shutdown(), and work_loop().
tasks_
std::queue<std::function<void()> > mock_executor::tasks_ private
Examples
executor_example.cpp.
Definition at line 185 of file executor_example.cpp.
Referenced by execute(), execute_delayed(), shutdown(), and work_loop().
workers_
std::vector<std::thread> mock_executor::workers_ private
Examples
executor_example.cpp.
Definition at line 184 of file executor_example.cpp.
Referenced by mock_executor(), and shutdown().
The documentation for this class was generated from the following file:
examples/executor_example.cpp