Common System: kcenon::common::adapters::interface_adapter< Interface, Implementation > Class Template Reference
kcenon::common::adapters::interface_adapter< Interface, Implementation > Class Template Reference
Interface adapter with type safety and depth tracking.
#include <adapter.h>
Public Member Functions
interface_adapter (std::shared_ptr< Implementation > impl)
Construct adapter with existing implementation.
virtual ~interface_adapter ()=default
std::shared_ptr< Implementation > unwrap () const
Get the underlying implementation.
bool is_wrapped_adapter () const
Check if this adapter wraps another adapter.
size_t get_wrapper_depth () const
Get the current wrapper depth.
size_t get_adapter_depth () const override
Get the adapter depth (implements adapter_base)
size_t get_type_id () const override
Get unique type ID for this adapter type.
Public Member Functions inherited from kcenon::common::adapters::adapter_base
virtual ~adapter_base ()=default
virtual bool is_adapter () const
Check if this is an adapter (always true for adapter_base)
Static Public Member Functions
static std::string adapter_type_name ()
Get type name for debugging.
static constexpr size_t max_depth ()
Get the maximum allowed wrapper depth.
static size_t get_static_type_id ()
Get static type ID for this adapter type.
Protected Attributes
std::shared_ptr< Implementation > impl_
Static Private Member Functions
static size_t generate_type_id ()
Generate a unique type ID.
static size_t calculate_depth (std::shared_ptr< Implementation > impl)
Calculate the depth of adapter wrapping.
Private Attributes
size_t wrapper_depth_
Static Private Attributes
static constexpr size_t max_wrapper_depth_ = 2
Detailed Description
template<typename Interface, typename Implementation>
class kcenon::common::adapters::interface_adapter< Interface, Implementation >
Interface adapter with type safety and depth tracking.
This template provides:
Type identification via type ID system (no RTTI)
Wrapper depth tracking to prevent infinite chains
Unwrap functionality to access underlying implementation
Maximum depth limit (default: 2) to prevent performance issues
Template Parameters
Interface The interface type being adapted to
Implementation The concrete implementation being wrapped
Definition at line 306 of file adapter.h.
Constructor & Destructor Documentation
interface_adapter()
template<typename Interface , typename Implementation > kcenon::common::adapters::interface_adapter< Interface, Implementation >::interface_adapter (std::shared_ptr< Implementation > impl) inline explicit
Construct adapter with existing implementation.
Parameters
impl Shared pointer to the implementation
Exceptions
std::runtime_error if wrapper depth exceeds maximum
Definition at line 313 of file adapter.h.
        : impl_(impl), wrapper_depth_(calculate_depth(impl)) {
        if (wrapper_depth_ > max_wrapper_depth_) {
            throw std::runtime_error(
                "Adapter chain too deep (" + std::to_string(wrapper_depth_) +
                " levels, max: " + std::to_string(max_wrapper_depth_) + ")");
        }
    }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::max_wrapper_depth_, and kcenon::common::adapters::interface_adapter< Interface, Implementation >::wrapper_depth_.
~interface_adapter()
template<typename Interface , typename Implementation > virtual kcenon::common::adapters::interface_adapter< Interface, Implementation >::~interface_adapter () virtual default
Member Function Documentation
adapter_type_name()
template<typename Interface , typename Implementation > static std::string kcenon::common::adapters::interface_adapter< Interface, Implementation >::adapter_type_name () inline static
Get type name for debugging.
Returns
Type name string
Definition at line 352 of file adapter.h.
{
        return "interface_adapter<Interface, Implementation>";
    }
calculate_depth()
template<typename Interface , typename Implementation > static size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::calculate_depth (std::shared_ptr< Implementation > impl) inline static private
Calculate the depth of adapter wrapping.
Parameters
impl The implementation to check
Returns
Depth level (0 for direct implementation, 1+ for wrapped)
Definition at line 398 of file adapter.h.
{
        if (!impl) {
            return 0;
        }
        if constexpr (std::is_base_of_v<adapter_base, Implementation>) {
#ifdef __cpp_rtti
            if (auto* base_adapter =
                    dynamic_cast<adapter_base*>(impl.get())) {
                return 1 + base_adapter->get_adapter_depth();
            }
            return 0;
#else
            auto* base_adapter = static_cast<adapter_base*>(impl.get());
            if (base_adapter && base_adapter->get_type_id() != 0) {
                return 1 + base_adapter->get_adapter_depth();
            }
            return 0;
#endif
        }
        return 0;
    }
generate_type_id()
template<typename Interface , typename Implementation > static size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::generate_type_id () inline static private
Generate a unique type ID.
Returns
Unique ID
Definition at line 388 of file adapter.h.
{
        static std::atomic<size_t> counter{0};
        return ++counter;
    }
Referenced by kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_static_type_id().
get_adapter_depth()
template<typename Interface , typename Implementation > size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_adapter_depth () const inline override virtual
Get the adapter depth (implements adapter_base)
Returns
Wrapper depth
Implements kcenon::common::adapters::adapter_base.
Definition at line 346 of file adapter.h.
{ return wrapper_depth_; }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::wrapper_depth_.
get_static_type_id()
template<typename Interface , typename Implementation > static size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_static_type_id () inline static
Get static type ID for this adapter type.
Returns
Type ID
Definition at line 372 of file adapter.h.
{
        static const size_t id = generate_type_id();
        return id;
    }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::generate_type_id().
Referenced by kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_type_id().
get_type_id()
template<typename Interface , typename Implementation > size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_type_id () const inline override virtual
Get unique type ID for this adapter type.
Returns
Type ID
Implements kcenon::common::adapters::adapter_base.
Definition at line 366 of file adapter.h.
{ return get_static_type_id(); }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_static_type_id().
get_wrapper_depth()
template<typename Interface , typename Implementation > size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_wrapper_depth () const inline
Get the current wrapper depth.
Returns
Number of adapter layers (0 for direct implementation)
Definition at line 340 of file adapter.h.
{ return wrapper_depth_; }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::wrapper_depth_.
is_wrapped_adapter()
template<typename Interface , typename Implementation > bool kcenon::common::adapters::interface_adapter< Interface, Implementation >::is_wrapped_adapter () const inline
Check if this adapter wraps another adapter.
Returns
true if wrapping another adapter, false otherwise
Definition at line 334 of file adapter.h.
{ return wrapper_depth_ > 0; }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::wrapper_depth_.
max_depth()
template<typename Interface , typename Implementation > static constexpr size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::max_depth () inline static constexpr
Get the maximum allowed wrapper depth.
Returns
Maximum depth value
Definition at line 360 of file adapter.h.
{ return max_wrapper_depth_; }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::max_wrapper_depth_.
unwrap()
template<typename Interface , typename Implementation > std::shared_ptr< Implementation > kcenon::common::adapters::interface_adapter< Interface, Implementation >::unwrap () const inline
Get the underlying implementation.
Returns
Shared pointer to the wrapped implementation
Definition at line 328 of file adapter.h.
{ return impl_; }
References kcenon::common::adapters::interface_adapter< Interface, Implementation >::impl_.
Member Data Documentation
impl_
template<typename Interface , typename Implementation > std::shared_ptr<Implementation> kcenon::common::adapters::interface_adapter< Interface, Implementation >::impl_ protected
Definition at line 378 of file adapter.h.
Referenced by kcenon::common::adapters::interface_adapter< Interface, Implementation >::unwrap().
max_wrapper_depth_
template<typename Interface , typename Implementation > size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::max_wrapper_depth_ = 2 static constexpr private
Definition at line 382 of file adapter.h.
Referenced by kcenon::common::adapters::interface_adapter< Interface, Implementation >::interface_adapter(), and kcenon::common::adapters::interface_adapter< Interface, Implementation >::max_depth().
wrapper_depth_
template<typename Interface , typename Implementation > size_t kcenon::common::adapters::interface_adapter< Interface, Implementation >::wrapper_depth_ private
Definition at line 381 of file adapter.h.
Referenced by kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_adapter_depth(), kcenon::common::adapters::interface_adapter< Interface, Implementation >::get_wrapper_depth(), kcenon::common::adapters::interface_adapter< Interface, Implementation >::interface_adapter(), and kcenon::common::adapters::interface_adapter< Interface, Implementation >::is_wrapped_adapter().
The documentation for this class was generated from the following file:
include/kcenon/common/adapters/adapter.h