Common System: kcenon::common::Optional< T > Class Template Reference
kcenon::common::Optional< T > Class Template Reference export
module kcenon.common
Optional type similar to std::optional with Rust-like API.
#include <core.h>
Public Types
using value_type = T
Type alias for the contained value type (for concept compatibility)
Public Member Functions
Optional ()
Optional (const T &value)
Optional (T &&value)
Optional (std::nullopt_t)
bool has_value () const
bool is_some () const
bool is_none () const
const T & value () const
T & value ()
const T & unwrap () const
Get value from optional (throws if None)
T unwrap_or (T default_value) const
template<typename F >
auto map (F &&func) const -> Optional< decltype(func(std::declval< T >()))>
Optional ()
Optional (const T &value)
Optional (T &&value)
Optional (std::nullopt_t)
bool has_value () const
bool is_some () const
bool is_none () const
const T & value () const
T & value ()
const T & unwrap () const
T unwrap_or (T default_value) const
template<typename F >
auto map (F &&func) const -> Optional< decltype(func(std::declval< T >()))>
Private Attributes
std::optional< T > value_
Detailed Description
template<typename T>
class kcenon::common::Optional< T >
Optional type similar to std::optional with Rust-like API.
Template Parameters
T The type of the contained value
Examples
unwrap_demo.cpp.
Definition at line 341 of file core.cppm.
Member Typedef Documentation
value_type
template<typename T > typedef T kcenon::common::Optional< T >::value_type = T export
Type alias for the contained value type (for concept compatibility)
Definition at line 471 of file core.h.
Constructor & Destructor Documentation
Optional() [1/8]
template<typename T > kcenon::common::Optional< T >::Optional () inline
Definition at line 477 of file core.h.
: value_(std::nullopt) {}
Referenced by kcenon::common::Optional< T >::map().
Optional() [2/8]
template<typename T > kcenon::common::Optional< T >::Optional (const T & value) inline
Definition at line 478 of file core.h.
: value_(value) {}
Optional() [3/8]
template<typename T > kcenon::common::Optional< T >::Optional (T && value) inline
Definition at line 479 of file core.h.
: value_(std::move(value)) {}
Optional() [4/8]
template<typename T > kcenon::common::Optional< T >::Optional (std::nullopt_t) inline
Definition at line 480 of file core.h.
: value_(std::nullopt) {}
Optional() [5/8]
template<typename T > kcenon::common::Optional< T >::Optional () inline export
Definition at line 349 of file core.cppm.
: value_(std::nullopt) {}
Optional() [6/8]
template<typename T > kcenon::common::Optional< T >::Optional (const T & value) inline export
Definition at line 350 of file core.cppm.
: value_(value) {}
Optional() [7/8]
template<typename T > kcenon::common::Optional< T >::Optional (T && value) inline export
Definition at line 351 of file core.cppm.
: value_(std::move(value)) {}
Optional() [8/8]
template<typename T > kcenon::common::Optional< T >::Optional (std::nullopt_t) inline export
Definition at line 352 of file core.cppm.
: value_(std::nullopt) {}
Member Function Documentation
has_value() [1/2]
template<typename T > bool kcenon::common::Optional< T >::has_value () const inline
Definition at line 482 of file core.h.
{ return value_.has_value(); }
References kcenon::common::Optional< T >::value_.
Referenced by kcenon::common::Optional< T >::map(), and kcenon::common::Optional< T >::unwrap().
has_value() [2/2]
template<typename T > bool kcenon::common::Optional< T >::has_value () const inline export
Definition at line 354 of file core.cppm.
{ return value_.has_value(); }
References kcenon::common::Optional< T >::value_.
is_none() [1/2]
template<typename T > bool kcenon::common::Optional< T >::is_none () const inline
Definition at line 484 of file core.h.
{ return !value_.has_value(); }
References kcenon::common::Optional< T >::value_.
is_none() [2/2]
template<typename T > bool kcenon::common::Optional< T >::is_none () const inline export
Definition at line 356 of file core.cppm.
{ return !value_.has_value(); }
References kcenon::common::Optional< T >::value_.
is_some() [1/2]
template<typename T > bool kcenon::common::Optional< T >::is_some () const inline
Definition at line 483 of file core.h.
{ return value_.has_value(); }
References kcenon::common::Optional< T >::value_.
is_some() [2/2]
template<typename T > bool kcenon::common::Optional< T >::is_some () const inline export
Definition at line 355 of file core.cppm.
{ return value_.has_value(); }
References kcenon::common::Optional< T >::value_.
map() [1/2]
template<typename T > template<typename F > auto kcenon::common::Optional< T >::map (F && func) const -> Optional<decltype(func(std::declval<T>()))> inline
Definition at line 521 of file core.h.
{
        using ReturnType = decltype(func(std::declval<T>()));
        if (has_value()) {
            return Optional<ReturnType>(func(value_.value()));
        } else {
            return Optional<ReturnType>(std::nullopt);
        }
    }
References kcenon::common::Optional< T >::has_value(), kcenon::common::Optional< T >::Optional(), and kcenon::common::Optional< T >::value_.
map() [2/2]
template<typename T > template<typename F > auto kcenon::common::Optional< T >::map (F && func) const -> Optional<decltype(func(std::declval<T>()))> inline export
Definition at line 386 of file core.cppm.
{
        using ReturnType = decltype(func(std::declval<T>()));
        if (has_value()) {
            return Optional<ReturnType>(func(value_.value()));
        } else {
            return Optional<ReturnType>(std::nullopt);
        }
    }
References kcenon::common::Optional< T >::has_value(), kcenon::common::Optional< T >::Optional(), and kcenon::common::Optional< T >::value_.
unwrap() [1/2]
template<typename T > const T & kcenon::common::Optional< T >::unwrap () const inline
Get value from optional (throws if None)
Exceptions
std::runtime_error if optional is None with detailed location info
Note
When source_location is available, error messages include file/line info
Definition at line 508 of file core.h.
{
        if (!has_value()) {
            throw std::runtime_error("Called unwrap on None");
        }
        return value_.value();
    }
References kcenon::common::Optional< T >::has_value(), and kcenon::common::Optional< T >::value_.
unwrap() [2/2]
template<typename T > const T & kcenon::common::Optional< T >::unwrap () const inline export
Definition at line 373 of file core.cppm.
{
        if (!has_value()) {
            throw std::runtime_error("Called unwrap on None");
        }
        return value_.value();
    }
References kcenon::common::Optional< T >::has_value(), and kcenon::common::Optional< T >::value_.
unwrap_or() [1/2]
template<typename T > T kcenon::common::Optional< T >::unwrap_or (T default_value) const inline
Definition at line 516 of file core.h.
{
        return value_.value_or(default_value);
    }
References kcenon::common::Optional< T >::value_.
unwrap_or() [2/2]
template<typename T > T kcenon::common::Optional< T >::unwrap_or (T default_value) const inline export
Definition at line 381 of file core.cppm.
{
        return value_.value_or(default_value);
    }
References kcenon::common::Optional< T >::value_.
value() [1/4]
template<typename T > T & kcenon::common::Optional< T >::value () inline
Definition at line 487 of file core.h.
{ return value_.value(); }
References kcenon::common::Optional< T >::value_.
value() [2/4]
template<typename T > T & kcenon::common::Optional< T >::value () inline export
Definition at line 359 of file core.cppm.
{ return value_.value(); }
References kcenon::common::Optional< T >::value_.
value() [3/4]
template<typename T > const T & kcenon::common::Optional< T >::value () const inline
Definition at line 486 of file core.h.
{ return value_.value(); }
References kcenon::common::Optional< T >::value_.
value() [4/4]
template<typename T > const T & kcenon::common::Optional< T >::value () const inline export
Definition at line 358 of file core.cppm.
{ return value_.value(); }
References kcenon::common::Optional< T >::value_.
Member Data Documentation
value_
template<typename T > std::optional< T > kcenon::common::Optional< T >::value_ export private
Definition at line 474 of file core.h.
Referenced by kcenon::common::Optional< T >::has_value(), kcenon::common::Optional< T >::is_none(), kcenon::common::Optional< T >::is_some(), kcenon::common::Optional< T >::map(), kcenon::common::Optional< T >::unwrap(), kcenon::common::Optional< T >::unwrap_or(), kcenon::common::Optional< T >::value(), and kcenon::common::Optional< T >::value().
The documentation for this class was generated from the following files:
include/kcenon/common/patterns/result/core.h
src/modules/result/core.cppm