Common System: kcenon::common::interfaces::NullLogger Class Reference
kcenon::common::interfaces::NullLogger Class Reference
A no-op logger implementation for fallback scenarios.
#include <global_logger_registry.h>
Public Member Functions
NullLogger ()=default
~NullLogger () override=default
VoidResult log (log_level, const std::string &) override
Log a message with specified level.
VoidResult log (log_level, std::string_view, const source_location &=source_location::current()) override
Log with source_location (no-op)
VoidResult log (const log_entry &) override
Log a structured entry.
bool is_enabled (log_level) const override
Check if logging is enabled for the specified level.
VoidResult set_level (log_level) override
Set the minimum log level.
log_level get_level () const override
Get the current minimum log level.
VoidResult flush () override
Flush any buffered log messages.
Public Member Functions inherited from kcenon::common::interfaces::ILogger
virtual ~ILogger ()=default
virtual ~ILogger ()=default
Detailed Description
A no-op logger implementation for fallback scenarios.
NullLogger provides a safe default when no logger has been registered. All logging operations are no-ops that return success without performing any actual logging. This prevents null pointer dereferences and allows code to function (silently) even when logging is not configured.
Note
Issue #177: Updated to support source_location-based logging.
Issue #217: Removed deprecated file/line/function API in v3.0.0.
Definition at line 52 of file global_logger_registry.h.
Constructor & Destructor Documentation
NullLogger()
kcenon::common::interfaces::NullLogger::NullLogger () default
~NullLogger()
kcenon::common::interfaces::NullLogger::~NullLogger () override default
Member Function Documentation
flush()
VoidResult kcenon::common::interfaces::NullLogger::flush () inline override virtual
Flush any buffered log messages.
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 87 of file global_logger_registry.h.
{
        return VoidResult::ok({});
    }
References kcenon::common::Result< T >::ok().
get_level()
log_level kcenon::common::interfaces::NullLogger::get_level () const inline override virtual
Get the current minimum log level.
Returns
Current minimum log level
Implements kcenon::common::interfaces::ILogger.
Definition at line 83 of file global_logger_registry.h.
{
        return log_level::off;
    }
References kcenon::common::interfaces::off.
is_enabled()
bool kcenon::common::interfaces::NullLogger::is_enabled (log_level level) const inline override virtual
Check if logging is enabled for the specified level.
Parameters
level Log level to check
Returns
true if logging is enabled for this level
Implements kcenon::common::interfaces::ILogger.
Definition at line 75 of file global_logger_registry.h.
{
        return false;
    }
log() [1/3]
VoidResult kcenon::common::interfaces::NullLogger::log (const log_entry & entry) inline override virtual
Log a structured entry.
Parameters
entry Log entry containing all information
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 71 of file global_logger_registry.h.
{
        return VoidResult::ok({});
    }
References kcenon::common::Result< T >::ok().
log() [2/3]
VoidResult kcenon::common::interfaces::NullLogger::log (log_level level, const std::string & message) inline override virtual
Log a message with specified level.
Parameters
level Log level
message Log message
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 57 of file global_logger_registry.h.
{
        return VoidResult::ok({});
    }
References kcenon::common::Result< T >::ok().
log() [3/3]
VoidResult kcenon::common::interfaces::NullLogger::log (log_level , std::string_view , const source_location & = source_location::current()) inline override virtual
Log with source_location (no-op)
Note
Issue #177: Preferred logging method with source_location.
Implements kcenon::common::interfaces::ILogger.
Definition at line 65 of file global_logger_registry.h.
{
        return VoidResult::ok({});
    }
References kcenon::common::Result< T >::ok().
set_level()
VoidResult kcenon::common::interfaces::NullLogger::set_level (log_level level) inline override virtual
Set the minimum log level.
Parameters
level Minimum level for messages to be logged
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 79 of file global_logger_registry.h.
{
        return VoidResult::ok({});
    }
References kcenon::common::Result< T >::ok().
The documentation for this class was generated from the following file:
include/kcenon/common/interfaces/global_logger_registry.h