Common System: kcenon::common::exception_mapper Class Reference
kcenon::common::exception_mapper Class Reference export
module kcenon.common
Maps standard exception types to appropriate error codes.
#include <utilities.h>
Static Public Member Functions
static error_info map_unknown_exception (const std::string &module="")
Map unknown exception (catch-all)
static error_info map_generic_exception (const std::exception &e, const std::string &module="")
Map generic exception.
static error_info map_unknown_exception (const std::string &module="")
static error_info map_generic_exception (const std::exception &e, const std::string &module="")
Detailed Description
Maps standard exception types to appropriate error codes.
Provides automatic error code assignment based on exception type, enabling more precise error handling without manual code specification.
Note: This class is kept for API compatibility but is no longer used internally. The try_catch functions now use multiple catch blocks for better performance.
Definition at line 122 of file utilities.cppm.
Member Function Documentation
map_generic_exception() [1/2]
static error_info kcenon::common::exception_mapper::map_generic_exception (const std::exception & e, const std::string & module = "") inline static
Map generic exception.
Parameters
e Exception object
module Module name
Returns
error_info
Definition at line 146 of file utilities.h.
{
        return error_info{error_codes::INTERNAL_ERROR, e.what(), module, "std::exception"};
    }
References kcenon::common::error_codes::INTERNAL_ERROR.
Referenced by kcenon::common::try_catch(), and kcenon::common::try_catch_void().
map_generic_exception() [2/2]
static error_info kcenon::common::exception_mapper::map_generic_exception (const std::exception & e, const std::string & module = "") inline static export
Definition at line 129 of file utilities.cppm.
{
        return error_info{error_codes::INTERNAL_ERROR, e.what(), module, "std::exception"};
    }
References kcenon::common::error_codes::INTERNAL_ERROR.
map_unknown_exception() [1/2]
static error_info kcenon::common::exception_mapper::map_unknown_exception (const std::string & module = "") inline static
Map unknown exception (catch-all)
Parameters
module Module name
Returns
error_info for unknown exception
Definition at line 135 of file utilities.h.
{
        return error_info{error_codes::INTERNAL_ERROR, "Unknown exception caught", module,
                         "Non-standard exception (not derived from std::exception)"};
    }
References kcenon::common::error_codes::INTERNAL_ERROR.
Referenced by kcenon::common::try_catch(), and kcenon::common::try_catch_void().
map_unknown_exception() [2/2]
static error_info kcenon::common::exception_mapper::map_unknown_exception (const std::string & module = "") inline static export
Definition at line 124 of file utilities.cppm.
{
        return error_info{error_codes::INTERNAL_ERROR, "Unknown exception caught", module,
                         "Non-standard exception (not derived from std::exception)"};
    }
References kcenon::common::error_codes::INTERNAL_ERROR.
The documentation for this class was generated from the following files:
include/kcenon/common/patterns/result/utilities.h
src/modules/result/utilities.cppm