Common System: kcenon::common::interfaces::scoped_timer Class Reference
kcenon::common::interfaces::scoped_timer Class Reference
RAII helper for automatic timing measurements.
#include <metric_collector_interface.h>
Public Member Functions
scoped_timer (IMetricCollector &collector, std::string_view name, metric_labels labels={})
Construct a scoped timer.
~scoped_timer ()
Destructor reports elapsed time to the collector.
scoped_timer (const scoped_timer &)=delete
scoped_timer & operator= (const scoped_timer &)=delete
scoped_timer (scoped_timer &&)=delete
scoped_timer & operator= (scoped_timer &&)=delete
std::chrono::nanoseconds elapsed () const
Get elapsed time since timer started.
Private Attributes
IMetricCollector & collector_
std::string name_
metric_labels labels_
std::chrono::steady_clock::time_point start_
Detailed Description
RAII helper for automatic timing measurements.
Measures elapsed time from construction to destruction and reports it to the metric collector. Useful for timing function execution, request handling, or any scoped operations.
Example usage:
void process_request() {
    scoped_timer timer(*collector, "request_processing_time",
                       {{"handler", "user_api"}});
    // ... do work ...
} // Timer automatically reports duration on scope exit
Note
This class is non-copyable and non-movable to prevent accidental double-reporting.
Definition at line 157 of file metric_collector_interface.h.
Constructor & Destructor Documentation
scoped_timer() [1/3]
kcenon::common::interfaces::scoped_timer::scoped_timer (IMetricCollector & collector, std::string_view name, metric_labels labels = {}) inline
Construct a scoped timer.
Parameters
collector Reference to the metric collector
name Metric name for the timing measurement
labels Optional dimensional labels
Definition at line 165 of file metric_collector_interface.h.
                                        {})
        : collector_(collector)
        , name_(name)
        , labels_(std::move(labels))
        , start_(std::chrono::steady_clock::now()) {}
~scoped_timer()
kcenon::common::interfaces::scoped_timer::~scoped_timer () inline
Destructor reports elapsed time to the collector.
Definition at line 176 of file metric_collector_interface.h.
                    {
        auto elapsed = std::chrono::steady_clock::now() - start_;
        collector_.timing(
            name_,
            std::chrono::duration_cast<std::chrono::nanoseconds>(elapsed),
            labels_);
    }
References collector_, elapsed(), labels_, name_, start_, and kcenon::common::interfaces::IMetricCollector::timing().
scoped_timer() [2/3]
kcenon::common::interfaces::scoped_timer::scoped_timer (const scoped_timer &) delete
scoped_timer() [3/3]
kcenon::common::interfaces::scoped_timer::scoped_timer (scoped_timer &&) delete
Member Function Documentation
elapsed()
std::chrono::nanoseconds kcenon::common::interfaces::scoped_timer::elapsed () const inline nodiscard
Get elapsed time since timer started.
Returns
Duration since construction
Definition at line 194 of file metric_collector_interface.h.
{
        return std::chrono::duration_cast<std::chrono::nanoseconds>(
            std::chrono::steady_clock::now() - start_);
    }
References start_.
Referenced by ~scoped_timer().
operator=() [1/2]
scoped_timer & kcenon::common::interfaces::scoped_timer::operator= (const scoped_timer &) delete
operator=() [2/2]
scoped_timer & kcenon::common::interfaces::scoped_timer::operator= (scoped_timer &&) delete
Member Data Documentation
collector_
IMetricCollector& kcenon::common::interfaces::scoped_timer::collector_ private
Definition at line 200 of file metric_collector_interface.h.
Referenced by ~scoped_timer().
labels_
metric_labels kcenon::common::interfaces::scoped_timer::labels_ private
Definition at line 202 of file metric_collector_interface.h.
Referenced by ~scoped_timer().
name_
std::string kcenon::common::interfaces::scoped_timer::name_ private
Definition at line 201 of file metric_collector_interface.h.
Referenced by ~scoped_timer().
start_
std::chrono::steady_clock::time_point kcenon::common::interfaces::scoped_timer::start_ private
Definition at line 203 of file metric_collector_interface.h.
Referenced by elapsed(), and ~scoped_timer().
The documentation for this class was generated from the following file:
include/kcenon/common/interfaces/monitoring/metric_collector_interface.h