Common System: kcenon::common::interfaces::RegistryAuditLog Class Reference
kcenon::common::interfaces::RegistryAuditLog Class Reference
Thread-safe audit log for registry operations.
#include <registry_audit_log.h>
Static Public Member Functions
static void log_event (const registry_event &event)
Log a registry event.
static void log_event (registry_event &&event)
Log a registry event (move version).
static std::vector< registry_event > get_events ()
Get all logged events.
static std::vector< registry_event > get_events_by_action (registry_action action)
Get events filtered by action type.
static std::vector< registry_event > get_events_in_range (std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end)
Get events within a time range.
static size_t event_count ()
Get the number of logged events.
static bool is_enabled ()
Check if audit logging is enabled.
static void set_enabled (bool enabled)
Enable or disable audit logging.
static void clear ()
Clear all audit events.
Private Member Functions
RegistryAuditLog ()=delete
Static Private Member Functions
static std::mutex & get_mutex ()
static std::vector< registry_event > & get_events_internal ()
static std::atomic< bool > & get_enabled_flag ()
Detailed Description
Thread-safe audit log for registry operations.
RegistryAuditLog provides a centralized, thread-safe mechanism for recording all mutations to global registries. The log is append-only to maintain integrity for security auditing.
Usage Example:
// Log a successful registration
RegistryAuditLog::log_event(registry_event(
    registry_action::register_service,
    "ILogger",
    source_location::current(),
    true
));
// Get all events for analysis
auto events = RegistryAuditLog::get_events();
for (const auto& event : events) {
    std::cout << to_string(event.action) << " on " << event.target_name
              << " at " << event.file << ":" << event.line << std::endl;
}
Definition at line 161 of file registry_audit_log.h.
Constructor & Destructor Documentation
RegistryAuditLog()
kcenon::common::interfaces::RegistryAuditLog::RegistryAuditLog () private delete
Member Function Documentation
clear()
void kcenon::common::interfaces::RegistryAuditLog::clear () inline static
Clear all audit events.
Warning
This is a destructive operation that removes all audit history. Use with caution and ensure proper authorization.
Note
This operation is allowed even when frozen for testing purposes, but a freeze event should be logged first in production.
Definition at line 333 of file registry_audit_log.h.
{
    std::lock_guard<std::mutex> lock(get_mutex());
    get_events_internal().clear();
}
References get_events_internal(), and get_mutex().
event_count()
size_t kcenon::common::interfaces::RegistryAuditLog::event_count () inline static
Get the number of logged events.
Returns
Number of events in the audit log
Definition at line 320 of file registry_audit_log.h.
{
    std::lock_guard<std::mutex> lock(get_mutex());
    return get_events_internal().size();
}
References get_events_internal(), and get_mutex().
get_enabled_flag()
std::atomic< bool > & kcenon::common::interfaces::RegistryAuditLog::get_enabled_flag () inline static private
Definition at line 265 of file registry_audit_log.h.
{
    static std::atomic<bool> enabled{true};
    return enabled;
}
Referenced by is_enabled(), and set_enabled().
get_events()
std::vector< registry_event > kcenon::common::interfaces::RegistryAuditLog::get_events () inline static
Get all logged events.
Returns a copy of all events in the audit log. This operation is thread-safe.
Returns
Vector of all registry events
Definition at line 288 of file registry_audit_log.h.
{
    std::lock_guard<std::mutex> lock(get_mutex());
    return get_events_internal();
}
References get_events_internal(), and get_mutex().
get_events_by_action()
std::vector< registry_event > kcenon::common::interfaces::RegistryAuditLog::get_events_by_action (registry_action action) inline static
Get events filtered by action type.
Parameters
action The action type to filter by
Returns
Vector of matching registry events
Definition at line 293 of file registry_audit_log.h.
{
    std::lock_guard<std::mutex> lock(get_mutex());
    std::vector<registry_event> result;
    for (const auto& event : get_events_internal()) {
        if (event.action == action) {
            result.push_back(event);
        }
    }
    return result;
}
References get_events_internal(), and get_mutex().
get_events_in_range()
std::vector< registry_event > kcenon::common::interfaces::RegistryAuditLog::get_events_in_range (std::chrono::system_clock::time_point start, std::chrono::system_clock::time_point end) inline static
Get events within a time range.
Parameters
start Start of time range
end End of time range
Returns
Vector of events within the time range
Definition at line 306 of file registry_audit_log.h.
{
    std::lock_guard<std::mutex> lock(get_mutex());
    std::vector<registry_event> result;
    for (const auto& event : get_events_internal()) {
        if (event.timestamp >= start && event.timestamp <= end) {
            result.push_back(event);
        }
    }
    return result;
}
References get_events_internal(), and get_mutex().
get_events_internal()
std::vector< registry_event > & kcenon::common::interfaces::RegistryAuditLog::get_events_internal () inline static private
Definition at line 260 of file registry_audit_log.h.
{
    static std::vector<registry_event> events;
    return events;
}
Referenced by clear(), event_count(), get_events(), get_events_by_action(), get_events_in_range(), log_event(), and log_event().
get_mutex()
std::mutex & kcenon::common::interfaces::RegistryAuditLog::get_mutex () inline static private
Definition at line 255 of file registry_audit_log.h.
{
    static std::mutex mutex;
    return mutex;
}
Referenced by clear(), event_count(), get_events(), get_events_by_action(), get_events_in_range(), log_event(), and log_event().
is_enabled()
bool kcenon::common::interfaces::RegistryAuditLog::is_enabled () inline static
Check if audit logging is enabled.
Returns
true if audit logging is enabled
Definition at line 325 of file registry_audit_log.h.
{
    return get_enabled_flag().load(std::memory_order_acquire);
}
References get_enabled_flag().
Referenced by log_event(), and log_event().
log_event() [1/2]
void kcenon::common::interfaces::RegistryAuditLog::log_event (const registry_event & event) inline static
Log a registry event.
Appends the event to the audit log. This operation is thread-safe.
Parameters
event The event to log
Definition at line 270 of file registry_audit_log.h.
{
    if (!is_enabled()) {
        return;
    }
    std::lock_guard<std::mutex> lock(get_mutex());
    get_events_internal().push_back(event);
}
References get_events_internal(), get_mutex(), and is_enabled().
Referenced by kcenon::common::di::service_container::check_already_registered(), kcenon::common::di::service_container::check_frozen_for_registration(), kcenon::common::di::service_container::clear(), kcenon::common::interfaces::GlobalLoggerRegistry::clear(), kcenon::common::di::service_container::freeze(), kcenon::common::interfaces::GlobalLoggerRegistry::freeze(), kcenon::common::interfaces::GlobalLoggerRegistry::register_factory(), kcenon::common::di::service_container::register_factory_internal(), kcenon::common::di::service_container::register_instance_internal(), kcenon::common::interfaces::GlobalLoggerRegistry::register_logger(), kcenon::common::interfaces::GlobalLoggerRegistry::set_default_factory(), kcenon::common::interfaces::GlobalLoggerRegistry::set_default_logger(), kcenon::common::di::service_container::unregister_internal(), and kcenon::common::interfaces::GlobalLoggerRegistry::unregister_logger().
log_event() [2/2]
void kcenon::common::interfaces::RegistryAuditLog::log_event (registry_event && event) inline static
Log a registry event (move version).
Parameters
event The event to log (moved)
Definition at line 279 of file registry_audit_log.h.
{
    if (!is_enabled()) {
        return;
    }
    std::lock_guard<std::mutex> lock(get_mutex());
    get_events_internal().push_back(std::move(event));
}
References get_events_internal(), get_mutex(), and is_enabled().
set_enabled()
void kcenon::common::interfaces::RegistryAuditLog::set_enabled (bool enabled) inline static
Enable or disable audit logging.
Parameters
enabled Whether to enable audit logging
Note
Disabling audit logging is a security-sensitive operation. Consider logging this action before disabling.
Definition at line 329 of file registry_audit_log.h.
{
    get_enabled_flag().store(enabled, std::memory_order_release);
}
References get_enabled_flag().
The documentation for this class was generated from the following file:
include/kcenon/common/interfaces/registry_audit_log.h