Common System: kcenon::common::logging::ConsoleLogger Class Reference
kcenon::common::logging::ConsoleLogger Class Reference export
module kcenon.common
Simple console logger implementation.
Public Member Functions
ConsoleLogger (interfaces::log_level level=interfaces::log_level::info)
VoidResult log (interfaces::log_level level, const std::string &message) override
Log a message with specified level.
VoidResult log (const interfaces::log_entry &entry) override
Log a structured entry.
bool is_enabled (interfaces::log_level level) const override
Check if logging is enabled for the specified level.
VoidResult set_level (interfaces::log_level level) override
Set the minimum log level.
interfaces::log_level get_level () const override
Get the current minimum log level.
VoidResult flush () override
Flush any buffered log messages.
Public Member Functions inherited from kcenon::common::interfaces::ILogger
virtual ~ILogger ()=default
virtual VoidResult log (log_level level, std::string_view message, const source_location &loc=source_location::current())
Log a message with source location information (C++20)
virtual ~ILogger ()=default
virtual VoidResult log (log_level level, std::string_view message, const source_location &loc=source_location::current())
Private Attributes
interfaces::log_level level_
Detailed Description
Simple console logger implementation.
Definition at line 103 of file logging.cppm.
Constructor & Destructor Documentation
ConsoleLogger()
kcenon::common::logging::ConsoleLogger::ConsoleLogger (interfaces::log_level level = interfaces::log_level::info) inline export
Definition at line 105 of file logging.cppm.
        : level_(level) {}
Member Function Documentation
flush()
VoidResult kcenon::common::logging::ConsoleLogger::flush () inline override export virtual
Flush any buffered log messages.
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 142 of file logging.cppm.
{
        std::cout.flush();
        return kcenon::common::ok();
    }
References kcenon::common::ok().
get_level()
interfaces::log_level kcenon::common::logging::ConsoleLogger::get_level () const inline override export virtual
Get the current minimum log level.
Returns
Current minimum log level
Implements kcenon::common::interfaces::ILogger.
Definition at line 138 of file logging.cppm.
{
        return level_;
    }
References level_.
is_enabled()
bool kcenon::common::logging::ConsoleLogger::is_enabled (interfaces::log_level level) const inline override export virtual
Check if logging is enabled for the specified level.
Parameters
level Log level to check
Returns
true if logging is enabled for this level
Implements kcenon::common::interfaces::ILogger.
Definition at line 129 of file logging.cppm.
{
        return static_cast<int>(level) >= static_cast<int>(level_);
    }
References level_.
Referenced by log(), and log().
log() [1/2]
VoidResult kcenon::common::logging::ConsoleLogger::log (const interfaces::log_entry & entry) inline override export virtual
Log a structured entry.
Parameters
entry Log entry containing all information
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 116 of file logging.cppm.
{
        if (!is_enabled(entry.level)) {
            return kcenon::common::ok();
        }
        std::cout << "[" << interfaces::to_string(entry.level) << "] "
                  << entry.message;
        if (!entry.file.empty()) {
            std::cout << " (" << entry.file << ":" << entry.line << ")";
        }
        std::cout << std::endl;
        return kcenon::common::ok();
    }
References kcenon::common::interfaces::log_entry::file, is_enabled(), kcenon::common::interfaces::log_entry::level, kcenon::common::interfaces::log_entry::line, kcenon::common::interfaces::log_entry::message, kcenon::common::ok(), and kcenon::common::interfaces::to_string().
log() [2/2]
VoidResult kcenon::common::logging::ConsoleLogger::log (interfaces::log_level level, const std::string & message) inline override export virtual
Log a message with specified level.
Parameters
level Log level
message Log message
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 108 of file logging.cppm.
{
        if (!is_enabled(level)) {
            return kcenon::common::ok();
        }
        std::cout << "[" << interfaces::to_string(level) << "] " << message << std::endl;
        return kcenon::common::ok();
    }
References is_enabled(), kcenon::common::ok(), and kcenon::common::interfaces::to_string().
set_level()
VoidResult kcenon::common::logging::ConsoleLogger::set_level (interfaces::log_level level) inline override export virtual
Set the minimum log level.
Parameters
level Minimum level for messages to be logged
Returns
VoidResult indicating success or error
Implements kcenon::common::interfaces::ILogger.
Definition at line 133 of file logging.cppm.
{
        level_ = level;
        return kcenon::common::ok();
    }
References level_, and kcenon::common::ok().
Member Data Documentation
level_
interfaces::log_level kcenon::common::logging::ConsoleLogger::level_ export private
Definition at line 148 of file logging.cppm.
Referenced by get_level(), is_enabled(), and set_level().
The documentation for this class was generated from the following file:
src/modules/logging.cppm