Common System: kcenon::common::adapters::adapter< T, Traits > Class Template Reference
kcenon::common::adapters::adapter< T, Traits > Class Template Reference
Unified adapter template for wrapping values or smart pointers.
#include <adapter.h>
Public Types
using value_type = typename Traits::value_type
using pointer_type = typename Traits::pointer_type
using reference_type = typename Traits::reference_type
using const_reference_type = typename Traits::const_reference_type
Public Member Functions
adapter (T value)
Construct adapter from value.
adapter ()
Default constructor (for default-constructible types)
auto get () const noexcept
Access raw pointer to the stored value.
decltype(auto) operator* () const
Dereference operator.
decltype(auto) operator* ()
Mutable dereference.
auto operator-> () const noexcept
Arrow operator.
auto operator-> () noexcept
Arrow operator (mutable)
auto weak () const
Get weak reference (only for shared_ptr)
operator bool () const noexcept
Check if adapter holds a valid value.
const T & value () const &noexcept
Get the underlying storage.
T & value () &noexcept
Get the underlying storage (mutable)
T value () &&noexcept
Move out the underlying storage.
T release () noexcept
Release ownership and return the underlying value.
Static Public Member Functions
static constexpr bool is_smart_pointer () noexcept
Check if adapter is holding a smart pointer type.
static constexpr bool supports_weak () noexcept
Check if weak references are supported.
Private Attributes
T value_
Detailed Description
template<typename T, typename Traits = adapter_traits<T>>
class kcenon::common::adapters::adapter< T, Traits >
Unified adapter template for wrapping values or smart pointers.
This adapter provides a consistent interface regardless of whether the wrapped type is a value, shared_ptr, or unique_ptr.
Template Parameters
T The type to wrap (can be value, shared_ptr, or unique_ptr)
Traits Adapter traits (automatically deduced)
// Value type
auto a1 = adapter<int>(42);
// Shared pointer
auto a2 = adapter(std::make_shared<MyClass>());
// Factory functions
auto a3 = make_adapter<MyClass>(args...);
auto a4 = make_shared_adapter<MyClass>(args...);
Examples
adapter_pattern_example.cpp.
Definition at line 118 of file adapter.h.
Member Typedef Documentation
const_reference_type
template<typename T , typename Traits = adapter_traits<T>> using kcenon::common::adapters::adapter< T, Traits >::const_reference_type = typename Traits::const_reference_type
Definition at line 123 of file adapter.h.
pointer_type
template<typename T , typename Traits = adapter_traits<T>> using kcenon::common::adapters::adapter< T, Traits >::pointer_type = typename Traits::pointer_type
Definition at line 121 of file adapter.h.
reference_type
template<typename T , typename Traits = adapter_traits<T>> using kcenon::common::adapters::adapter< T, Traits >::reference_type = typename Traits::reference_type
Definition at line 122 of file adapter.h.
value_type
template<typename T , typename Traits = adapter_traits<T>> using kcenon::common::adapters::adapter< T, Traits >::value_type = typename Traits::value_type
Definition at line 120 of file adapter.h.
Constructor & Destructor Documentation
adapter() [1/2]
template<typename T , typename Traits = adapter_traits<T>> kcenon::common::adapters::adapter< T, Traits >::adapter (T value) inline explicit
Construct adapter from value.
Parameters
value The value to wrap
Definition at line 129 of file adapter.h.
: value_(std::move(value)) {}
adapter() [2/2]
template<typename T , typename Traits = adapter_traits<T>> kcenon::common::adapters::adapter< T, Traits >::adapter () inline
Default constructor (for default-constructible types)
Definition at line 134 of file adapter.h.
: value_() {}
Member Function Documentation
get()
template<typename T , typename Traits = adapter_traits<T>> auto kcenon::common::adapters::adapter< T, Traits >::get () const inline noexcept
Access raw pointer to the stored value.
Returns
Pointer to the value
Examples
adapter_pattern_example.cpp.
Definition at line 140 of file adapter.h.
{
        if constexpr (Traits::is_smart_pointer) {
            return value_.get();
        } else {
            return std::addressof(value_);
        }
    }
References kcenon::common::adapters::adapter< T, Traits >::value_.
Referenced by kcenon::common::adapters::adapter< T, Traits >::operator->(), kcenon::common::adapters::adapter< T, Traits >::operator->(), and use_service().
is_smart_pointer()
template<typename T , typename Traits = adapter_traits<T>> static constexpr bool kcenon::common::adapters::adapter< T, Traits >::is_smart_pointer () inline static constexpr noexcept
Check if adapter is holding a smart pointer type.
Returns
true if smart pointer, false if value type
Definition at line 228 of file adapter.h.
{
        return Traits::is_smart_pointer;
    }
operator bool()
template<typename T , typename Traits = adapter_traits<T>> kcenon::common::adapters::adapter< T, Traits >::operator bool () const inline explicit noexcept
Check if adapter holds a valid value.
Returns
true if valid, false otherwise
Definition at line 194 of file adapter.h.
{
        if constexpr (Traits::is_smart_pointer) {
            return static_cast<bool>(value_);
        } else {
            return true; // Value types are always valid
        }
    }
References kcenon::common::adapters::adapter< T, Traits >::value_.
operator*() [1/2]
template<typename T , typename Traits = adapter_traits<T>> decltype(auto) kcenon::common::adapters::adapter< T, Traits >::operator* () inline
Mutable dereference.
Definition at line 163 of file adapter.h.
{
        if constexpr (Traits::is_smart_pointer) {
            return *value_;
        } else {
            return value_;
        }
    }
References kcenon::common::adapters::adapter< T, Traits >::value_.
operator*() [2/2]
template<typename T , typename Traits = adapter_traits<T>> decltype(auto) kcenon::common::adapters::adapter< T, Traits >::operator* () const inline
Dereference operator.
Returns
Reference to the stored value
Definition at line 152 of file adapter.h.
{
        if constexpr (Traits::is_smart_pointer) {
            return *value_;
        } else {
            return value_;
        }
    }
References kcenon::common::adapters::adapter< T, Traits >::value_.
operator->() [1/2]
template<typename T , typename Traits = adapter_traits<T>> auto kcenon::common::adapters::adapter< T, Traits >::operator-> () const inline noexcept
Arrow operator.
Returns
Pointer to the value for member access
Definition at line 175 of file adapter.h.
{ return get(); }
References kcenon::common::adapters::adapter< T, Traits >::get().
operator->() [2/2]
template<typename T , typename Traits = adapter_traits<T>> auto kcenon::common::adapters::adapter< T, Traits >::operator-> () inline noexcept
Arrow operator (mutable)
Definition at line 180 of file adapter.h.
{ return get(); }
References kcenon::common::adapters::adapter< T, Traits >::get().
release()
template<typename T , typename Traits = adapter_traits<T>> T kcenon::common::adapters::adapter< T, Traits >::release () inline noexcept
Release ownership and return the underlying value.
Returns
The stored value (moved)
Definition at line 222 of file adapter.h.
{ return std::move(value_); }
References kcenon::common::adapters::adapter< T, Traits >::value_.
supports_weak()
template<typename T , typename Traits = adapter_traits<T>> static constexpr bool kcenon::common::adapters::adapter< T, Traits >::supports_weak () inline static constexpr noexcept
Check if weak references are supported.
Returns
true if supports weak references
Definition at line 236 of file adapter.h.
{
        return Traits::supports_weak;
    }
value() [1/3]
template<typename T , typename Traits = adapter_traits<T>> T kcenon::common::adapters::adapter< T, Traits >::value () && inline noexcept
Move out the underlying storage.
Definition at line 216 of file adapter.h.
{ return std::move(value_); }
References kcenon::common::adapters::adapter< T, Traits >::value_.
value() [2/3]
template<typename T , typename Traits = adapter_traits<T>> T & kcenon::common::adapters::adapter< T, Traits >::value () & inline noexcept
Get the underlying storage (mutable)
Definition at line 211 of file adapter.h.
{ return value_; }
References kcenon::common::adapters::adapter< T, Traits >::value_.
value() [3/3]
template<typename T , typename Traits = adapter_traits<T>> const T & kcenon::common::adapters::adapter< T, Traits >::value () const & inline noexcept
Get the underlying storage.
Returns
Reference to the stored value
Definition at line 206 of file adapter.h.
{ return value_; }
References kcenon::common::adapters::adapter< T, Traits >::value_.
weak()
template<typename T , typename Traits = adapter_traits<T>> auto kcenon::common::adapters::adapter< T, Traits >::weak () const inline
Get weak reference (only for shared_ptr)
Returns
weak_ptr to the stored value
Definition at line 186 of file adapter.h.
{
        return typename Traits::weak_type(value_);
    }
References kcenon::common::adapters::adapter< T, Traits >::value_.
Member Data Documentation
value_
template<typename T , typename Traits = adapter_traits<T>> T kcenon::common::adapters::adapter< T, Traits >::value_ private
Definition at line 241 of file adapter.h.
Referenced by kcenon::common::adapters::adapter< T, Traits >::get(), kcenon::common::adapters::adapter< T, Traits >::operator bool(), kcenon::common::adapters::adapter< T, Traits >::operator*(), kcenon::common::adapters::adapter< T, Traits >::operator*(), kcenon::common::adapters::adapter< T, Traits >::release(), kcenon::common::adapters::adapter< T, Traits >::value(), kcenon::common::adapters::adapter< T, Traits >::value(), kcenon::common::adapters::adapter< T, Traits >::value(), and kcenon::common::adapters::adapter< T, Traits >::weak().
The documentation for this class was generated from the following file:
include/kcenon/common/adapters/adapter.h