Common System: example_executor_provider Class Reference
example_executor_provider Class Reference
Public Member Functions
std::shared_ptr< IExecutor > get_executor () override
Get the default executor instance.
std::shared_ptr< IExecutor > create_executor (size_t worker_count) override
Create a new executor with specific configuration.
Public Member Functions inherited from kcenon::common::interfaces::IExecutorProvider
virtual ~IExecutorProvider ()=default
virtual ~IExecutorProvider ()=default
Private Attributes
std::shared_ptr< IExecutor > default_executor_
Detailed Description
Example of executor provider pattern
Examples
executor_example.cpp.
Definition at line 282 of file executor_example.cpp.
Member Function Documentation
create_executor()
std::shared_ptr< IExecutor > example_executor_provider::create_executor (size_t worker_count) inline override virtual
Create a new executor with specific configuration.
Parameters
worker_count Number of worker threads
Returns
Shared pointer to the new executor
Implements kcenon::common::interfaces::IExecutorProvider.
Examples
executor_example.cpp.
Definition at line 291 of file executor_example.cpp.
{
        return std::make_shared<mock_executor>(worker_count);
    }
Referenced by get_executor().
get_executor()
std::shared_ptr< IExecutor > example_executor_provider::get_executor () inline override virtual
Get the default executor instance.
Returns
Shared pointer to the executor
Implements kcenon::common::interfaces::IExecutorProvider.
Examples
executor_example.cpp.
Definition at line 284 of file executor_example.cpp.
{
        if (!default_executor_) {
            default_executor_ = create_executor(4);
        }
        return default_executor_;
    }
References create_executor(), and default_executor_.
Referenced by main().
Member Data Documentation
default_executor_
std::shared_ptr<IExecutor> example_executor_provider::default_executor_ private
Examples
executor_example.cpp.
Definition at line 296 of file executor_example.cpp.
Referenced by get_executor().
The documentation for this class was generated from the following file:
examples/executor_example.cpp