var concepts =
[
    [ "kcenon", "namespacekcenon.html", [
      [ "common", "namespacekcenon_1_1common.html", [
        [ "concepts", "namespacekcenon_1_1common_1_1concepts.html", [
          [ "Invocable", "conceptkcenon_1_1common_1_1concepts_1_1Invocable.html", null ],
          [ "VoidCallable", "conceptkcenon_1_1common_1_1concepts_1_1VoidCallable.html", null ],
          [ "ReturnsResult", "conceptkcenon_1_1common_1_1concepts_1_1ReturnsResult.html", null ],
          [ "NoexceptCallable", "conceptkcenon_1_1common_1_1concepts_1_1NoexceptCallable.html", null ],
          [ "Predicate", "conceptkcenon_1_1common_1_1concepts_1_1Predicate.html", null ],
          [ "UnaryFunction", "conceptkcenon_1_1common_1_1concepts_1_1UnaryFunction.html", null ],
          [ "BinaryFunction", "conceptkcenon_1_1common_1_1concepts_1_1BinaryFunction.html", null ],
          [ "JobLike", "conceptkcenon_1_1common_1_1concepts_1_1JobLike.html", null ],
          [ "ExecutorLike", "conceptkcenon_1_1common_1_1concepts_1_1ExecutorLike.html", null ],
          [ "TaskFactory", "conceptkcenon_1_1common_1_1concepts_1_1TaskFactory.html", null ],
          [ "AsyncCallable", "conceptkcenon_1_1common_1_1concepts_1_1AsyncCallable.html", null ],
          [ "DelayedCallable", "conceptkcenon_1_1common_1_1concepts_1_1DelayedCallable.html", null ],
          [ "Container", "conceptkcenon_1_1common_1_1concepts_1_1Container.html", null ],
          [ "SequenceContainer", "conceptkcenon_1_1common_1_1concepts_1_1SequenceContainer.html", null ],
          [ "AssociativeContainer", "conceptkcenon_1_1common_1_1concepts_1_1AssociativeContainer.html", null ],
          [ "MappingContainer", "conceptkcenon_1_1common_1_1concepts_1_1MappingContainer.html", null ],
          [ "ResizableContainer", "conceptkcenon_1_1common_1_1concepts_1_1ResizableContainer.html", null ],
          [ "ClearableContainer", "conceptkcenon_1_1common_1_1concepts_1_1ClearableContainer.html", null ],
          [ "InsertableContainer", "conceptkcenon_1_1common_1_1concepts_1_1InsertableContainer.html", null ],
          [ "ErasableContainer", "conceptkcenon_1_1common_1_1concepts_1_1ErasableContainer.html", null ],
          [ "RandomAccessContainer", "conceptkcenon_1_1common_1_1concepts_1_1RandomAccessContainer.html", null ],
          [ "BoundedContainer", "conceptkcenon_1_1common_1_1concepts_1_1BoundedContainer.html", null ],
          [ "ThreadSafeContainer", "conceptkcenon_1_1common_1_1concepts_1_1ThreadSafeContainer.html", null ],
          [ "PoolableContainer", "conceptkcenon_1_1common_1_1concepts_1_1PoolableContainer.html", null ],
          [ "CircularBuffer", "conceptkcenon_1_1common_1_1concepts_1_1CircularBuffer.html", null ],
          [ "Resultable", "conceptkcenon_1_1common_1_1concepts_1_1Resultable.html", null ],
          [ "Unwrappable", "conceptkcenon_1_1common_1_1concepts_1_1Unwrappable.html", null ],
          [ "Mappable", "conceptkcenon_1_1common_1_1concepts_1_1Mappable.html", null ],
          [ "Chainable", "conceptkcenon_1_1common_1_1concepts_1_1Chainable.html", null ],
          [ "MonadicResult", "conceptkcenon_1_1common_1_1concepts_1_1MonadicResult.html", null ],
          [ "OptionalLike", "conceptkcenon_1_1common_1_1concepts_1_1OptionalLike.html", null ],
          [ "ErrorInfo", "conceptkcenon_1_1common_1_1concepts_1_1ErrorInfo.html", null ],
          [ "ValueOrError", "conceptkcenon_1_1common_1_1concepts_1_1ValueOrError.html", null ],
          [ "EventType", "conceptkcenon_1_1common_1_1concepts_1_1EventType.html", null ],
          [ "EventHandler", "conceptkcenon_1_1common_1_1concepts_1_1EventHandler.html", null ],
          [ "EventFilter", "conceptkcenon_1_1common_1_1concepts_1_1EventFilter.html", null ],
          [ "TimestampedEvent", "conceptkcenon_1_1common_1_1concepts_1_1TimestampedEvent.html", null ],
          [ "NamedEvent", "conceptkcenon_1_1common_1_1concepts_1_1NamedEvent.html", null ],
          [ "ErrorEvent", "conceptkcenon_1_1common_1_1concepts_1_1ErrorEvent.html", null ],
          [ "MetricEvent", "conceptkcenon_1_1common_1_1concepts_1_1MetricEvent.html", null ],
          [ "ModuleLifecycleEvent", "conceptkcenon_1_1common_1_1concepts_1_1ModuleLifecycleEvent.html", null ],
          [ "FullErrorEvent", "conceptkcenon_1_1common_1_1concepts_1_1FullErrorEvent.html", null ],
          [ "FullMetricEvent", "conceptkcenon_1_1common_1_1concepts_1_1FullMetricEvent.html", null ],
          [ "EventBusLike", "conceptkcenon_1_1common_1_1concepts_1_1EventBusLike.html", null ],
          [ "LogLevelEnumLike", "conceptkcenon_1_1common_1_1concepts_1_1LogLevelEnumLike.html", null ],
          [ "BasicLogger", "conceptkcenon_1_1common_1_1concepts_1_1BasicLogger.html", null ],
          [ "LevelAwareLogger", "conceptkcenon_1_1common_1_1concepts_1_1LevelAwareLogger.html", null ],
          [ "FlushableLogger", "conceptkcenon_1_1common_1_1concepts_1_1FlushableLogger.html", null ],
          [ "StructuredLogger", "conceptkcenon_1_1common_1_1concepts_1_1StructuredLogger.html", null ],
          [ "LoggerLike", "conceptkcenon_1_1common_1_1concepts_1_1LoggerLike.html", null ],
          [ "LoggerProviderLike", "conceptkcenon_1_1common_1_1concepts_1_1LoggerProviderLike.html", null ],
          [ "LoggerRegistryLike", "conceptkcenon_1_1common_1_1concepts_1_1LoggerRegistryLike.html", null ],
          [ "CounterMetric", "conceptkcenon_1_1common_1_1concepts_1_1CounterMetric.html", null ],
          [ "GaugeMetric", "conceptkcenon_1_1common_1_1concepts_1_1GaugeMetric.html", null ],
          [ "HistogramMetric", "conceptkcenon_1_1common_1_1concepts_1_1HistogramMetric.html", null ],
          [ "TimingMetric", "conceptkcenon_1_1common_1_1concepts_1_1TimingMetric.html", null ],
          [ "MetricCollectorLike", "conceptkcenon_1_1common_1_1concepts_1_1MetricCollectorLike.html", null ],
          [ "NamedImplementation", "conceptkcenon_1_1common_1_1concepts_1_1NamedImplementation.html", null ],
          [ "MetricCollectorProviderLike", "conceptkcenon_1_1common_1_1concepts_1_1MetricCollectorProviderLike.html", null ],
          [ "ServiceInterface", "conceptkcenon_1_1common_1_1concepts_1_1ServiceInterface.html", null ],
          [ "ServiceImplementation", "conceptkcenon_1_1common_1_1concepts_1_1ServiceImplementation.html", null ],
          [ "ServiceFactory", "conceptkcenon_1_1common_1_1concepts_1_1ServiceFactory.html", null ],
          [ "SimpleServiceFactory", "conceptkcenon_1_1common_1_1concepts_1_1SimpleServiceFactory.html", null ],
          [ "ServiceContainerLike", "conceptkcenon_1_1common_1_1concepts_1_1ServiceContainerLike.html", null ],
          [ "ServiceScopeLike", "conceptkcenon_1_1common_1_1concepts_1_1ServiceScopeLike.html", null ],
          [ "InjectableService", "conceptkcenon_1_1common_1_1concepts_1_1InjectableService.html", null ],
          [ "SharedService", "conceptkcenon_1_1common_1_1concepts_1_1SharedService.html", null ],
          [ "ConfigSection", "conceptkcenon_1_1common_1_1concepts_1_1ConfigSection.html", null ],
          [ "Validatable", "conceptkcenon_1_1common_1_1concepts_1_1Validatable.html", null ],
          [ "ServiceWithDependencies", "conceptkcenon_1_1common_1_1concepts_1_1ServiceWithDependencies.html", null ],
          [ "InitializableService", "conceptkcenon_1_1common_1_1concepts_1_1InitializableService.html", null ],
          [ "DisposableService", "conceptkcenon_1_1common_1_1concepts_1_1DisposableService.html", null ],
          [ "ModuleRegistrar", "conceptkcenon_1_1common_1_1concepts_1_1ModuleRegistrar.html", null ],
          [ "HttpSender", "conceptkcenon_1_1common_1_1concepts_1_1HttpSender.html", null ],
          [ "HttpAvailabilityChecker", "conceptkcenon_1_1common_1_1concepts_1_1HttpAvailabilityChecker.html", null ],
          [ "HttpClientLike", "conceptkcenon_1_1common_1_1concepts_1_1HttpClientLike.html", null ],
          [ "HttpClientProviderLike", "conceptkcenon_1_1common_1_1concepts_1_1HttpClientProviderLike.html", null ],
          [ "UdpConnectable", "conceptkcenon_1_1common_1_1concepts_1_1UdpConnectable.html", null ],
          [ "UdpSender", "conceptkcenon_1_1common_1_1concepts_1_1UdpSender.html", null ],
          [ "UdpConnectionStatus", "conceptkcenon_1_1common_1_1concepts_1_1UdpConnectionStatus.html", null ],
          [ "UdpClientLike", "conceptkcenon_1_1common_1_1concepts_1_1UdpClientLike.html", null ],
          [ "UdpClientProviderLike", "conceptkcenon_1_1common_1_1concepts_1_1UdpClientProviderLike.html", null ],
          [ "TransportClient", "conceptkcenon_1_1common_1_1concepts_1_1TransportClient.html", null ],
          [ "Sendable", "conceptkcenon_1_1common_1_1concepts_1_1Sendable.html", null ],
          [ "Receivable", "conceptkcenon_1_1common_1_1concepts_1_1Receivable.html", null ]
        ] ],
        [ "EnumSerializable", "conceptkcenon_1_1common_1_1EnumSerializable.html", null ]
      ] ]
    ] ]
];