Common System: examples/health_check_example.cpp File Reference
health_check_example.cpp File Reference
#include <kcenon/common/interfaces/monitoring/health_check.h>
#include <kcenon/common/patterns/result.h>
#include <chrono>
#include <iostream>
#include <memory>
#include <string>
#include <vector>
Classes
class app_liveness_check
class cache_readiness_check
class database_dependency_check
Functions
std::string status_string (health_status status)
int main ()
Function Documentation
main()
int main ()
Definition at line 124 of file health_check_example.cpp.
{
    std::cout << "=== Health Check Example ===\n\n";
    // 1. Health check type utilities
    std::cout << "1. Health check types:\n";
    std::cout << "   liveness -> \"" << to_string(health_check_type::liveness) << "\"\n";
    std::cout << "   readiness -> \"" << to_string(health_check_type::readiness) << "\"\n";
    std::cout << "   dependency -> \"" << to_string(health_check_type::dependency) << "\"\n";
    auto parsed = health_check_type_from_string("readiness");
    if (parsed.is_ok())
    {
        std::cout << "   \"readiness\" -> " << to_string(parsed.value()) << "\n";
    }
    // 2. Create health checks
    std::cout << "\n2. Running health checks:\n";
    std::vector<std::unique_ptr<health_check>> checks;
    checks.push_back(std::make_unique<app_liveness_check>());
    checks.push_back(std::make_unique<cache_readiness_check>(true));
    checks.push_back(std::make_unique<database_dependency_check>(true));
    bool all_healthy = true;
    for (const auto& hc : checks)
    {
        auto result = hc->check();
        std::cout << "   [" << to_string(hc->get_type()) << "] " << hc->get_name() << ": "
                  << status_string(result.status) << " - " << result.message
                  << " (critical=" << (hc->is_critical() ? "yes" : "no")
                  << ", timeout=" << hc->get_timeout().count() << "ms)\n";
        if (result.status == health_status::unhealthy && hc->is_critical())
        {
            all_healthy = false;
        }
    }
    std::cout << "\n   Overall: " << (all_healthy ? "HEALTHY" : "UNHEALTHY") << "\n";
    // 3. Simulate a failure scenario
    std::cout << "\n3. Simulating database failure:\n";
    database_dependency_check db_down(false);
    auto result = db_down.check();
    std::cout << "   " << db_down.get_name() << ": " << status_string(result.status) << " - "
              << result.message << "\n";
    std::cout << "\nDone.\n";
    return 0;
}
References database_dependency_check::check(), database_dependency_check::get_name(), kcenon::common::interfaces::health_check_type_from_string(), status_string(), and kcenon::common::interfaces::to_string().
status_string()
std::string status_string (health_status status)
Examples
health_check_example.cpp.
Definition at line 109 of file health_check_example.cpp.
{
    switch (status)
    {
    case health_status::healthy:
        return "HEALTHY";
    case health_status::degraded:
        return "DEGRADED";
    case health_status::unhealthy:
        return "UNHEALTHY";
    default:
        return "UNKNOWN";
    }
}
Referenced by main().