Common System: kcenon::common::logging Namespace Reference
kcenon::common::logging Namespace Reference
Classes
class ConsoleLogger
Simple console logger implementation.
Functions
VoidResult log (interfaces::log_level level, std::string_view message, const source_location &loc=source_location::current())
Log a message with the specified level and source location.
VoidResult log (interfaces::log_level level, std::string_view message, const std::shared_ptr< interfaces::ILogger > &logger, const source_location &loc=source_location::current())
Log a message to a specific logger with source location.
VoidResult log (interfaces::log_level level, std::string_view message, const std::string &logger_name, const source_location &loc=source_location::current())
Log a message to a named logger with source location.
VoidResult log_trace (std::string_view message, const source_location &loc=source_location::current())
Log a trace-level message.
VoidResult log_debug (std::string_view message, const source_location &loc=source_location::current())
Log a debug-level message.
VoidResult log_info (std::string_view message, const source_location &loc=source_location::current())
Log an info-level message.
VoidResult log_warning (std::string_view message, const source_location &loc=source_location::current())
Log a warning-level message.
VoidResult log_error (std::string_view message, const source_location &loc=source_location::current())
Log an error-level message.
VoidResult log_critical (std::string_view message, const source_location &loc=source_location::current())
Log a critical-level message.
VoidResult log_trace_to (const std::string &logger_name, std::string_view message, const source_location &loc=source_location::current())
Log a trace-level message to a named logger.
VoidResult log_debug_to (const std::string &logger_name, std::string_view message, const source_location &loc=source_location::current())
Log a debug-level message to a named logger.
VoidResult log_info_to (const std::string &logger_name, std::string_view message, const source_location &loc=source_location::current())
Log an info-level message to a named logger.
VoidResult log_warning_to (const std::string &logger_name, std::string_view message, const source_location &loc=source_location::current())
Log a warning-level message to a named logger.
VoidResult log_error_to (const std::string &logger_name, std::string_view message, const source_location &loc=source_location::current())
Log an error-level message to a named logger.
VoidResult log_critical_to (const std::string &logger_name, std::string_view message, const source_location &loc=source_location::current())
Log a critical-level message to a named logger.
bool is_enabled (interfaces::log_level level)
Check if a log level is enabled for the default logger.
bool is_enabled (interfaces::log_level level, const std::string &logger_name)
Check if a log level is enabled for a named logger.
VoidResult flush ()
Flush all buffered log messages for the default logger.
VoidResult flush (const std::string &logger_name)
Flush all buffered log messages for a named logger.
void kcenon::common::logging::log_trace (std::shared_ptr< interfaces::ILogger > logger, std::string_view message)
Log a trace message.
void kcenon::common::logging::log_debug (std::shared_ptr< interfaces::ILogger > logger, std::string_view message)
Log a debug message.
void kcenon::common::logging::log_info (std::shared_ptr< interfaces::ILogger > logger, std::string_view message)
Log an info message.
void kcenon::common::logging::log_warning (std::shared_ptr< interfaces::ILogger > logger, std::string_view message)
Log a warning message.
void kcenon::common::logging::log_error (std::shared_ptr< interfaces::ILogger > logger, std::string_view message)
Log an error message.
void kcenon::common::logging::log_critical (std::shared_ptr< interfaces::ILogger > logger, std::string_view message)
Log a critical message.
std::shared_ptr< interfaces::ILogger > kcenon::common::logging::make_console_logger (interfaces::log_level level=interfaces::log_level::info)
Create a console logger.
Function Documentation
flush() [1/2]
VoidResult kcenon::common::logging::flush () inline
Flush all buffered log messages for the default logger.
Returns
VoidResult indicating success or error
Definition at line 341 of file log_functions.h.
{
    return interfaces::get_logger()->flush();
}
References kcenon::common::interfaces::get_logger().
flush() [2/2]
VoidResult kcenon::common::logging::flush (const std::string & logger_name) inline
Flush all buffered log messages for a named logger.
Parameters
logger_name Name of the logger
Returns
VoidResult indicating success or error
Definition at line 351 of file log_functions.h.
{
    return interfaces::get_logger(logger_name)->flush();
}
References kcenon::common::interfaces::get_logger().
is_enabled() [1/2]
bool kcenon::common::logging::is_enabled (interfaces::log_level level) inline
Check if a log level is enabled for the default logger.
Use this to avoid expensive message formatting when the log level is disabled.
Parameters
level Log level to check
Returns
true if the level is enabled
Definition at line 321 of file log_functions.h.
{
    return interfaces::get_logger()->is_enabled(level);
}
References kcenon::common::interfaces::get_logger().
is_enabled() [2/2]
bool kcenon::common::logging::is_enabled (interfaces::log_level level, const std::string & logger_name) inline
Check if a log level is enabled for a named logger.
Parameters
level Log level to check
logger_name Name of the logger
Returns
true if the level is enabled
Definition at line 332 of file log_functions.h.
{
    return interfaces::get_logger(logger_name)->is_enabled(level);
}
References kcenon::common::interfaces::get_logger().
log() [1/3]
VoidResult kcenon::common::logging::log (interfaces::log_level level, std::string_view message, const source_location & loc = source_location::current()) inline
Log a message with the specified level and source location.
Primary logging function that logs to the default logger with automatic source location capture.
Parameters
level Log level for the message
message Message to log
loc Source location (automatically captured at call site)
Returns
VoidResult indicating success or error
Note
Issue #177: Now uses ILogger's source_location-based overload directly for improved efficiency (avoids string copies for file/function names).
Definition at line 66 of file log_functions.h.
{
    auto logger = interfaces::get_logger();
    if (!logger->is_enabled(level)) {
        return VoidResult::ok({});
    }
    // Use the new source_location-based interface (Issue #177)
    return logger->log(level, message, loc);
}
References kcenon::common::interfaces::get_logger(), and kcenon::common::Result< T >::ok().
Referenced by log_critical(), log_critical_to(), log_debug(), log_debug_to(), log_error(), log_error_to(), log_info(), log_info_to(), log_trace(), log_trace_to(), log_warning(), and log_warning_to().
log() [2/3]
VoidResult kcenon::common::logging::log (interfaces::log_level level, std::string_view message, const std::shared_ptr< interfaces::ILogger > & logger, const source_location & loc = source_location::current()) inline
Log a message to a specific logger with source location.
Allows logging to a named or custom logger while still capturing source location information.
Parameters
level Log level for the message
message Message to log
logger Logger instance to use
loc Source location (automatically captured at call site)
Returns
VoidResult indicating success or error
Note
Issue #177: Now uses ILogger's source_location-based overload directly.
Definition at line 91 of file log_functions.h.
{
    if (!logger || !logger->is_enabled(level)) {
        return VoidResult::ok({});
    }
    // Use the new source_location-based interface (Issue #177)
    return logger->log(level, message, loc);
}
References kcenon::common::Result< T >::ok().
log() [3/3]
VoidResult kcenon::common::logging::log (interfaces::log_level level, std::string_view message, const std::string & logger_name, const source_location & loc = source_location::current()) inline
Log a message to a named logger with source location.
Retrieves a logger by name from GlobalLoggerRegistry and logs to it.
Parameters
level Log level for the message
message Message to log
logger_name Name of the logger in the registry
loc Source location (automatically captured at call site)
Returns
VoidResult indicating success or error
Note
Issue #177: Now uses ILogger's source_location-based overload directly.
Definition at line 115 of file log_functions.h.
{
    auto logger = interfaces::get_logger(logger_name);
    if (!logger->is_enabled(level)) {
        return VoidResult::ok({});
    }
    // Use the new source_location-based interface (Issue #177)
    return logger->log(level, message, loc);
}
References kcenon::common::interfaces::get_logger(), and kcenon::common::Result< T >::ok().
log_critical() [1/2]
void kcenon::common::logging::log_critical (std::shared_ptr< interfaces::ILogger > logger, std::string_view message) inline export
Log a critical message.
Definition at line 89 of file logging.cppm.
{
    if (logger && logger->is_enabled(interfaces::log_level::critical)) {
        logger->log(interfaces::log_level::critical, message);
    }
}
References kcenon::common::interfaces::critical.
log_critical() [2/2]
VoidResult kcenon::common::logging::log_critical (std::string_view message, const source_location & loc = source_location::current()) inline
Log a critical-level message.
Critical messages indicate severe failures that may cause the application to terminate or enter an unstable state.
Parameters
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 214 of file log_functions.h.
{
    return log(interfaces::log_level::critical, message, loc);
}
References kcenon::common::interfaces::critical, and log().
log_critical_to()
VoidResult kcenon::common::logging::log_critical_to (const std::string & logger_name, std::string_view message, const source_location & loc = source_location::current()) inline
Log a critical-level message to a named logger.
Parameters
logger_name Name of the logger
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 302 of file log_functions.h.
{
    return log(interfaces::log_level::critical, message, logger_name, loc);
}
References kcenon::common::interfaces::critical, and log().
log_debug() [1/2]
void kcenon::common::logging::log_debug (std::shared_ptr< interfaces::ILogger > logger, std::string_view message) inline export
Log a debug message.
Definition at line 53 of file logging.cppm.
{
    if (logger && logger->is_enabled(interfaces::log_level::debug)) {
        logger->log(interfaces::log_level::debug, message);
    }
}
References kcenon::common::interfaces::debug.
log_debug() [2/2]
VoidResult kcenon::common::logging::log_debug (std::string_view message, const source_location & loc = source_location::current()) inline
Log a debug-level message.
Debug messages are used for development-time debugging information.
Parameters
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 155 of file log_functions.h.
{
    return log(interfaces::log_level::debug, message, loc);
}
References kcenon::common::interfaces::debug, and log().
log_debug_to()
VoidResult kcenon::common::logging::log_debug_to (const std::string & logger_name, std::string_view message, const source_location & loc = source_location::current()) inline
Log a debug-level message to a named logger.
Parameters
logger_name Name of the logger
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 246 of file log_functions.h.
{
    return log(interfaces::log_level::debug, message, logger_name, loc);
}
References kcenon::common::interfaces::debug, and log().
log_error() [1/2]
void kcenon::common::logging::log_error (std::shared_ptr< interfaces::ILogger > logger, std::string_view message) inline export
Log an error message.
Definition at line 80 of file logging.cppm.
{
    if (logger && logger->is_enabled(interfaces::log_level::error)) {
        logger->log(interfaces::log_level::error, message);
    }
}
References kcenon::common::interfaces::error.
log_error() [2/2]
VoidResult kcenon::common::logging::log_error (std::string_view message, const source_location & loc = source_location::current()) inline
Log an error-level message.
Error messages indicate failures that may require attention but don't necessarily terminate the application.
Parameters
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 199 of file log_functions.h.
{
    return log(interfaces::log_level::error, message, loc);
}
References kcenon::common::interfaces::error, and log().
log_error_to()
VoidResult kcenon::common::logging::log_error_to (const std::string & logger_name, std::string_view message, const source_location & loc = source_location::current()) inline
Log an error-level message to a named logger.
Parameters
logger_name Name of the logger
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 288 of file log_functions.h.
{
    return log(interfaces::log_level::error, message, logger_name, loc);
}
References kcenon::common::interfaces::error, and log().
log_info() [1/2]
void kcenon::common::logging::log_info (std::shared_ptr< interfaces::ILogger > logger, std::string_view message) inline export
Log an info message.
Definition at line 62 of file logging.cppm.
{
    if (logger && logger->is_enabled(interfaces::log_level::info)) {
        logger->log(interfaces::log_level::info, message);
    }
}
References kcenon::common::interfaces::info.
log_info() [2/2]
VoidResult kcenon::common::logging::log_info (std::string_view message, const source_location & loc = source_location::current()) inline
Log an info-level message.
Info messages convey general operational information.
Parameters
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 169 of file log_functions.h.
{
    return log(interfaces::log_level::info, message, loc);
}
References kcenon::common::interfaces::info, and log().
log_info_to()
VoidResult kcenon::common::logging::log_info_to (const std::string & logger_name, std::string_view message, const source_location & loc = source_location::current()) inline
Log an info-level message to a named logger.
Parameters
logger_name Name of the logger
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 260 of file log_functions.h.
{
    return log(interfaces::log_level::info, message, logger_name, loc);
}
References kcenon::common::interfaces::info, and log().
log_trace() [1/2]
void kcenon::common::logging::log_trace (std::shared_ptr< interfaces::ILogger > logger, std::string_view message) inline export
Log a trace message.
Definition at line 44 of file logging.cppm.
{
    if (logger && logger->is_enabled(interfaces::log_level::trace)) {
        logger->log(interfaces::log_level::trace, message);
    }
}
References kcenon::common::interfaces::trace.
log_trace() [2/2]
VoidResult kcenon::common::logging::log_trace (std::string_view message, const source_location & loc = source_location::current()) inline
Log a trace-level message.
Trace messages are the most verbose and typically used for detailed debugging information.
Parameters
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 141 of file log_functions.h.
{
    return log(interfaces::log_level::trace, message, loc);
}
References log(), and kcenon::common::interfaces::trace.
log_trace_to()
VoidResult kcenon::common::logging::log_trace_to (const std::string & logger_name, std::string_view message, const source_location & loc = source_location::current()) inline
Log a trace-level message to a named logger.
Parameters
logger_name Name of the logger
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 232 of file log_functions.h.
{
    return log(interfaces::log_level::trace, message, logger_name, loc);
}
References log(), and kcenon::common::interfaces::trace.
log_warning() [1/2]
void kcenon::common::logging::log_warning (std::shared_ptr< interfaces::ILogger > logger, std::string_view message) inline export
Log a warning message.
Definition at line 71 of file logging.cppm.
{
    if (logger && logger->is_enabled(interfaces::log_level::warning)) {
        logger->log(interfaces::log_level::warning, message);
    }
}
References kcenon::common::interfaces::warning.
log_warning() [2/2]
VoidResult kcenon::common::logging::log_warning (std::string_view message, const source_location & loc = source_location::current()) inline
Log a warning-level message.
Warning messages indicate potentially problematic situations that don't prevent the application from functioning.
Parameters
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 184 of file log_functions.h.
{
    return log(interfaces::log_level::warning, message, loc);
}
References log(), and kcenon::common::interfaces::warning.
log_warning_to()
VoidResult kcenon::common::logging::log_warning_to (const std::string & logger_name, std::string_view message, const source_location & loc = source_location::current()) inline
Log a warning-level message to a named logger.
Parameters
logger_name Name of the logger
message Message to log
loc Source location (automatically captured)
Returns
VoidResult indicating success or error
Definition at line 274 of file log_functions.h.
{
    return log(interfaces::log_level::warning, message, logger_name, loc);
}
References log(), and kcenon::common::interfaces::warning.
make_console_logger()
std::shared_ptr< interfaces::ILogger > kcenon::common::logging::make_console_logger (interfaces::log_level level = interfaces::log_level::info) inline export
Create a console logger.
Definition at line 154 of file logging.cppm.
{
    return std::make_shared<ConsoleLogger>(level);
}