Common System: kcenon::common::source_location Struct Reference
kcenon::common::source_location Struct Reference export
module kcenon.common
C++17-compatible source_location implementation using compiler builtins.
#include <source_location.h>
Public Member Functions
constexpr source_location (const char *file=__builtin_FILE(), const char *function=__builtin_FUNCTION(), int line=__builtin_LINE()) noexcept
constexpr const char * file_name () const noexcept
constexpr const char * function_name () const noexcept
constexpr int line () const noexcept
constexpr int column () const noexcept
constexpr source_location (const char *file=__builtin_FILE(), const char *function=__builtin_FUNCTION(), int line=__builtin_LINE()) noexcept
constexpr const char * file_name () const noexcept
constexpr const char * function_name () const noexcept
constexpr int line () const noexcept
constexpr int column () const noexcept
constexpr source_location (const char *file=__builtin_FILE(), const char *function=__builtin_FUNCTION(), int line=__builtin_LINE()) noexcept
constexpr const char * file_name () const noexcept
constexpr const char * function_name () const noexcept
constexpr int line () const noexcept
constexpr int column () const noexcept
Static Public Member Functions
static constexpr source_location current (const char *file=__builtin_FILE(), const char *function=__builtin_FUNCTION(), int line=__builtin_LINE()) noexcept
static constexpr source_location current (const char *file=__builtin_FILE(), const char *function=__builtin_FUNCTION(), int line=__builtin_LINE()) noexcept
static constexpr source_location current (const char *file=__builtin_FILE(), const char *function=__builtin_FUNCTION(), int line=__builtin_LINE()) noexcept
Private Attributes
const char * file_
const char * function_
int line_
int column_
Detailed Description
C++17-compatible source_location implementation using compiler builtins.
Definition at line 54 of file utils.cppm.
Constructor & Destructor Documentation
source_location() [1/3]
kcenon::common::source_location::source_location (const char * file = __builtin_FILE(), const char * function = __builtin_FUNCTION(), int line = __builtin_LINE()) inline constexpr noexcept
Definition at line 36 of file source_location.h.
            : file_(file), function_(function), line_(line), column_(0) {}
Referenced by current().
source_location() [2/3]
kcenon::common::source_location::source_location (const char * file = __builtin_FILE(), const char * function = __builtin_FUNCTION(), int line = __builtin_LINE()) inline constexpr export noexcept
Definition at line 48 of file core.cppm.
        : file_(file), function_(function), line_(line), column_(0) {}
source_location() [3/3]
kcenon::common::source_location::source_location (const char * file = __builtin_FILE(), const char * function = __builtin_FUNCTION(), int line = __builtin_LINE()) inline constexpr export noexcept
Definition at line 56 of file utils.cppm.
        : file_(file), function_(function), line_(line), column_(0) {}
Member Function Documentation
column() [1/3]
int kcenon::common::source_location::column () const inline constexpr noexcept
Definition at line 46 of file source_location.h.
{ return column_; }
References column_.
column() [2/3]
int kcenon::common::source_location::column () const inline constexpr export noexcept
Definition at line 58 of file core.cppm.
{ return column_; }
References column_.
column() [3/3]
int kcenon::common::source_location::column () const inline constexpr export noexcept
Definition at line 66 of file utils.cppm.
{ return column_; }
References column_.
current() [1/3]
static constexpr source_location kcenon::common::source_location::current (const char * file = __builtin_FILE(), const char * function = __builtin_FUNCTION(), int line = __builtin_LINE()) inline static constexpr noexcept
Definition at line 49 of file source_location.h.
                   {
            return source_location(file, function, line);
        }
References line(), and source_location().
Referenced by kcenon::common::di::service_container::check_already_registered(), kcenon::common::di::service_container::check_frozen_for_registration(), kcenon::common::di::service_container::clear(), kcenon::common::interfaces::GlobalLoggerRegistry::clear(), kcenon::common::di::service_container::freeze(), kcenon::common::interfaces::GlobalLoggerRegistry::freeze(), kcenon::common::interfaces::GlobalLoggerRegistry::register_factory(), kcenon::common::di::service_container::register_factory_internal(), kcenon::common::di::service_container::register_instance_internal(), kcenon::common::interfaces::GlobalLoggerRegistry::register_logger(), kcenon::common::interfaces::GlobalLoggerRegistry::set_default_factory(), kcenon::common::interfaces::GlobalLoggerRegistry::set_default_logger(), kcenon::common::di::service_container::unregister_internal(), and kcenon::common::interfaces::GlobalLoggerRegistry::unregister_logger().
current() [2/3]
static constexpr source_location kcenon::common::source_location::current (const char * file = __builtin_FILE(), const char * function = __builtin_FUNCTION(), int line = __builtin_LINE()) inline static constexpr export noexcept
Definition at line 60 of file core.cppm.
               {
        return source_location(file, function, line);
    }
References line(), and source_location().
current() [3/3]
static constexpr source_location kcenon::common::source_location::current (const char * file = __builtin_FILE(), const char * function = __builtin_FUNCTION(), int line = __builtin_LINE()) inline static constexpr export noexcept
Definition at line 68 of file utils.cppm.
               {
        return source_location(file, function, line);
    }
References line(), and source_location().
file_name() [1/3]
const char * kcenon::common::source_location::file_name () const inline constexpr noexcept
Definition at line 43 of file source_location.h.
{ return file_; }
References file_.
file_name() [2/3]
const char * kcenon::common::source_location::file_name () const inline constexpr export noexcept
Definition at line 55 of file core.cppm.
{ return file_; }
References file_.
file_name() [3/3]
const char * kcenon::common::source_location::file_name () const inline constexpr export noexcept
Definition at line 63 of file utils.cppm.
{ return file_; }
References file_.
function_name() [1/3]
const char * kcenon::common::source_location::function_name () const inline constexpr noexcept
Definition at line 44 of file source_location.h.
{ return function_; }
References function_.
function_name() [2/3]
const char * kcenon::common::source_location::function_name () const inline constexpr export noexcept
Definition at line 56 of file core.cppm.
{ return function_; }
References function_.
function_name() [3/3]
const char * kcenon::common::source_location::function_name () const inline constexpr export noexcept
Definition at line 64 of file utils.cppm.
{ return function_; }
References function_.
line() [1/3]
int kcenon::common::source_location::line () const inline constexpr noexcept
Definition at line 45 of file source_location.h.
{ return line_; }
References line_.
Referenced by current().
line() [2/3]
int kcenon::common::source_location::line () const inline constexpr export noexcept
Definition at line 57 of file core.cppm.
{ return line_; }
References line_.
line() [3/3]
int kcenon::common::source_location::line () const inline constexpr export noexcept
Definition at line 65 of file utils.cppm.
{ return line_; }
References line_.
Member Data Documentation
column_
int kcenon::common::source_location::column_ export private
Definition at line 61 of file source_location.h.
Referenced by column().
file_
const char * kcenon::common::source_location::file_ export private
Definition at line 58 of file source_location.h.
Referenced by file_name().
function_
const char * kcenon::common::source_location::function_ export private
Definition at line 59 of file source_location.h.
Referenced by function_name().
line_
int kcenon::common::source_location::line_ export private
Definition at line 60 of file source_location.h.
Referenced by line().
The documentation for this struct was generated from the following files:
include/kcenon/common/utils/source_location.h
src/modules/result/core.cppm
src/modules/utils.cppm