Common System: kcenon::common::detail::event_type_id< T > Struct Template Reference
kcenon::common::detail::event_type_id< T > Struct Template Reference
Generate unique type ID for each event type using std::type_index.
#include <event_bus.h>
Static Public Member Functions
static size_t id ()
Detailed Description
template<typename T>
struct kcenon::common::detail::event_type_id< T >
Generate unique type ID for each event type using std::type_index.
IMPLEMENTATION:
This implementation uses std::type_index and std::hash to generate consistent type IDs across all translation units. Unlike counter-based approaches, this ensures that the same event type always receives the same ID regardless of instantiation order.
BENEFITS:
Consistent IDs across translation units (TUs)
No initialization order dependencies
Type-safe without relying on manual registration
Events published in one TU will correctly match handlers in another TU
THREAD SAFETY:
The hash is computed once per type and cached in a static variable
C++11 guarantees thread-safe static local initialization
No race conditions or synchronization needed
COMPATIBILITY:
Requires RTTI (typeid support)
Hash collision risk is negligible (std::hash quality)
IDs are stable across program runs on the same platform/compiler
NOTE: For RTTI-free environments, consider enabling ENABLE_MONITORING_INTEGRATION which provides alternative type identification mechanisms.
Definition at line 84 of file event_bus.h.
Member Function Documentation
id()
template<typename T > static size_t kcenon::common::detail::event_type_id< T >::id () inline static
Definition at line 85 of file event_bus.h.
{
            // Use std::type_index hash for deterministic, consistent IDs
            static const size_t type_id = std::hash<std::type_index>{}(std::type_index(typeid(T)));
            return type_id;
        }
Referenced by kcenon::common::simple_event_bus::publish(), kcenon::common::simple_event_bus::publish(), kcenon::common::simple_event_bus::subscribe(), and kcenon::common::simple_event_bus::subscribe().
The documentation for this struct was generated from the following file:
include/kcenon/common/patterns/event_bus.h