Common System: examples/unwrap_demo.cpp File Reference
unwrap_demo.cpp File Reference
#include "kcenon/common/patterns/result.h"
#include <iostream>
#include <string>
Functions
Result< int > divide (int numerator, int denominator)
Optional< std::string > find_user (int id)
void demonstrate_improved_error_messages ()
int main ()
Function Documentation
demonstrate_improved_error_messages()
void demonstrate_improved_error_messages ()
Examples
unwrap_demo.cpp.
Definition at line 45 of file unwrap_demo.cpp.
{
    std::cout << "=== Improved unwrap() Error Messages Demo ===\n\n";
    // Demo 1: Result<T> unwrap with detailed error info
    std::cout << "1. Result<T>::unwrap() with error:\n";
    std::cout << "-----------------------------------\n";
    try {
        auto result = divide(10, 0);
        // This will throw with detailed source location
        int value = result.unwrap();  // Line will be captured automatically
        std::cout << "Value: " << value << "\n";
    } catch (const std::exception& e) {
        std::cout << "Exception caught:\n" << e.what() << "\n\n";
    }
    // Demo 2: Optional<T> unwrap with source location
    std::cout << "2. Optional<T>::unwrap() with None:\n";
    std::cout << "------------------------------------\n";
    try {
        auto user = find_user(999);
        // This will throw with source location
        std::string name = user.unwrap();  // Line will be captured automatically
        std::cout << "User: " << name << "\n";
    } catch (const std::exception& e) {
        std::cout << "Exception caught:\n" << e.what() << "\n\n";
    }
    // Demo 3: Safe alternatives (recommended)
    std::cout << "3. Safe alternatives to unwrap():\n";
    std::cout << "----------------------------------\n";
    auto result = divide(10, 0);
    // Option A: unwrap_or with default value
    int value1 = result.unwrap_or(0);
    std::cout << "unwrap_or(0): " << value1 << "\n";
    // Option B: Check before accessing
    if (result.is_ok()) {
        std::cout << "Value: " << result.value() << "\n";
    } else {
        auto error = result.error();
        std::cout << "Error: " << error.message << "\n";
        std::cout << "  Code: " << error.code << "\n";
        std::cout << "  Module: " << error.module << "\n";
    }
    // Option C: is_ok() check with value() access
    if (result.is_ok()) {
        std::cout << "Value via is_ok check: " << result.value() << "\n";
    } else {
        std::cout << "Result is in error state\n";
    }
    // Option D: Monadic operations
    auto doubled = divide(10, 2)
        .map([](int x) { return x * 2; })
        .unwrap_or(-1);
    std::cout << "Monadic map result: " << doubled << "\n";
    std::cout << "\n=== Demo Complete ===\n";
}
References divide(), and find_user().
Referenced by main().
divide()
Result< int > divide (int numerator, int denominator)
Definition at line 25 of file unwrap_demo.cpp.
{
    if (denominator == 0) {
        return make_error<int>(
            -1,
            "Division by zero",
            "math_module",
            "Cannot divide by zero"
        );
    }
    return ok(numerator / denominator);
}
References kcenon::common::make_error(), and kcenon::common::ok().
Referenced by demonstrate_improved_error_messages().
find_user()
Optional< std::string > find_user (int id)
Examples
unwrap_demo.cpp.
Definition at line 38 of file unwrap_demo.cpp.
{
    if (id == 42) {
        return Optional<std::string>("Alice");
    }
    return Optional<std::string>(std::nullopt);
}
Referenced by demonstrate_improved_error_messages().
main()
int main ()
Definition at line 108 of file unwrap_demo.cpp.
           {
    demonstrate_improved_error_messages();
    return 0;
}
References demonstrate_improved_error_messages().