#!/usr/bin/env bash
# collect-notices.sh — Collect and bundle NOTICE files from Apache-2.0 dependencies
#
# Usage:
#   ./scripts/collect-notices.sh [VCPKG_INSTALLED_DIR]
#
# Arguments:
#   VCPKG_INSTALLED_DIR  Path to vcpkg installed directory (default: build/vcpkg_installed)
#
# Output:
#   NOTICES file in the repository root containing all upstream NOTICE content
#
# Apache-2.0 License §4.4 requires reproducing the contents of any NOTICE file
# provided by upstream dependencies. This script automates that collection.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
VCPKG_DIR="${1:-${VCPKG_INSTALLED_DIR:-build/vcpkg_installed}}"
OUTPUT_FILE="$REPO_ROOT/NOTICES"

# Apache-2.0 dependencies that may ship NOTICE files
APACHE2_DEPS=(
    openssl
    grpc
    benchmark
    opentelemetry-cpp
    abseil
    mongo-cxx-driver
    mongo-c-driver
    protobuf
)

echo "=============================================="
echo "Apache-2.0 NOTICE File Collector"
echo "=============================================="
echo "vcpkg dir:   $VCPKG_DIR"
echo "output:      $OUTPUT_FILE"
echo ""

# Start building the NOTICES file
cat > "$OUTPUT_FILE" <<'HEADER'
NOTICES — Apache-2.0 Dependency Attribution
============================================

This file contains the contents of NOTICE files from Apache-2.0 licensed
dependencies, as required by Apache License 2.0 §4.4.

Generated by: scripts/collect-notices.sh
HEADER

echo "Generated on: $(date -u '+%Y-%m-%d %H:%M UTC')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

found_count=0
not_found_count=0
no_notice_deps=()

# Search for NOTICE files in vcpkg installed directory
if [ -d "$VCPKG_DIR" ]; then
    echo "Scanning vcpkg installed directory..."

    # Find all NOTICE* files
    while IFS= read -r notice_file; do
        dep_name=$(echo "$notice_file" | sed -E 's|.*/share/([^/]+)/.*|\1|')
        echo "  Found: $dep_name -> $notice_file"

        {
            echo "--------------------------------------------"
            echo "Dependency: $dep_name"
            echo "Source:     $notice_file"
            echo "--------------------------------------------"
            cat "$notice_file"
            echo ""
            echo ""
        } >> "$OUTPUT_FILE"

        found_count=$((found_count + 1))
    done < <(find "$VCPKG_DIR" -type f \( -name "NOTICE" -o -name "NOTICE.txt" -o -name "NOTICE.md" \) 2>/dev/null || true)
else
    echo "WARNING: vcpkg installed directory not found at: $VCPKG_DIR"
    echo "  This is expected if dependencies are not installed locally."
    echo "  Run 'cmake --preset <preset>' first, or pass the correct path."
    echo ""
fi

# Also search in common known locations for source builds
for dep in "${APACHE2_DEPS[@]}"; do
    # Check if we already found a NOTICE for this dep
    if grep -q "Dependency: $dep" "$OUTPUT_FILE" 2>/dev/null; then
        continue
    fi
    no_notice_deps+=("$dep")
    not_found_count=$((not_found_count + 1))
done

# Append audit section
{
    echo "=============================================="
    echo "NOTICE File Audit Summary"
    echo "=============================================="
    echo ""
    echo "Apache-2.0 dependencies with NOTICE files:    $found_count"
    echo "Apache-2.0 dependencies without NOTICE files: $not_found_count"
    echo ""
    if [ ${#no_notice_deps[@]} -gt 0 ]; then
        echo "Dependencies without NOTICE files (no §4.4 obligation):"
        for dep in "${no_notice_deps[@]}"; do
            echo "  - $dep"
        done
    fi
    echo ""
    echo "Note: Apache-2.0 §4.4 only requires reproducing NOTICE file contents"
    echo "when the upstream project provides one. Dependencies listed above as"
    echo "'without NOTICE files' have no §4.4 obligation."
} >> "$OUTPUT_FILE"

echo ""
echo "Results:"
echo "  NOTICE files found:     $found_count"
echo "  Deps without NOTICE:    $not_found_count"
echo "  Output written to:      $OUTPUT_FILE"
echo ""

if [ $found_count -eq 0 ] && [ ! -d "$VCPKG_DIR" ]; then
    echo "No NOTICE files collected (vcpkg directory not available)."
    echo "The NOTICES file contains the audit template."
fi
